{
  "hash": "59485c04626b54b813f3011a8ce78219",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Working with distribution functions\"\n---\n\n\n\nHeights, blood pressures, measurement errors, log-transformed gene-expression\nvalues — measure enough of almost anything in biology and the values tend to pile\nup into the same bell-shaped curve: the **normal distribution**. Once your data\nfollow that curve, you'll want to ask questions of it. *What fraction of samples\nfall below some cutoff? Which value marks the top 5%? Give me twenty random draws\nto simulate an experiment.* R answers each of those with a different function.\n\nThe catch is remembering which function does which job. This chapter is a\n**visual guide**: for every function we pair the R call with a picture of exactly\nwhat it measures on the bell curve, because the difference between a *probability*,\na *density*, and a *quantile* is far easier to see than to memorize. It's genuinely\nhard to reason about these functions without a shape to point at — so a shape is\nwhat we'll build for each one.\n\n## What you'll learn\n\n- Use `pnorm()` to turn a value into a probability (the area under the curve to its\n  left).\n- Use `dnorm()` to get the height (density) of the curve at a value.\n- Use `qnorm()` to go the other direction — from a probability back to a value.\n- Use `rnorm()` to draw random samples from a normal distribution.\n- Combine these functions to answer real questions about normally distributed\n  data, such as IQ scores.\n\n::: {.callout-tip}\n## One naming rule for *every* distribution\n\nR builds these names from a one-letter prefix plus the distribution: **d** for\ndensity, **p** for probability, **q** for quantile, **r** for random. Learn it once\nand it transfers everywhere — `dbinom`/`pbinom`/`qbinom`/`rbinom` for the binomial,\n`dt`/`pt`/`qt`/`rt` for the t-distribution we meet in the next chapter,\n`dpois`/`ppois`/… for the Poisson. Here we use the `…norm` family for the normal.\n:::\n\n\n::: {.cell}\n\n:::\n\n\nThe four functions, at a glance:\n\n| Function | Input | Output |\n|----------|-------|--------|\n| `pnorm`  | a value `q` | P(X < q): area under the curve to the **left** of `q` |\n| `dnorm`  | a value `x` | the **height** of the density curve at `x` |\n| `qnorm`  | a probability from 0 to 1 | the value `x` where P(X < x) equals that probability |\n| `rnorm`  | a count `n` | `n` random samples from the distribution |\n\n: Functions for the normal distribution {#tbl-norm-funcs}\n\nIn one sentence each: `pnorm` gives the area to the left of a point, `dnorm` gives\nthe height of the curve at a point, `qnorm` is the inverse of `pnorm` (probability\nback to value), and `rnorm` generates random samples. The rest of the chapter\nunpacks them one at a time.\n\n## pnorm\n\n`pnorm` answers the question \"what fraction of the distribution lies to the\n**left** of this value?\" If you don't supply a mean and standard deviation, R\nassumes the *standard normal* (mean 0, standard deviation 1). The help page gives\nthis template:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(q, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)\n```\n:::\n\n\nYou hand it `q`, a value on the x-axis, and it returns the area under the curve to\nthe left of that point. The mean sits dead centre and splits the curve in half, so:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(0)    # half the distribution is below the mean\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5\n```\n\n\n:::\n\n```{.r .cell-code}\npnorm(1)    # ~84% is below one standard deviation above the mean\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8413447\n```\n\n\n:::\n\n```{.r .cell-code}\npnorm(-1)   # ~16% is below one standard deviation below it\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1586553\n```\n\n\n:::\n:::\n\n\nThe figures below show each of those as a shaded area.\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The pnorm function takes a quantile (value on the x-axis) and returns the area under the curve to the left of that value.](norm_files/figure-html/fig-pnorm-1.png){#fig-pnorm-1 width=672}\n:::\n\n::: {.cell-output-display}\n![The pnorm function takes a quantile (value on the x-axis) and returns the area under the curve to the left of that value.](norm_files/figure-html/fig-pnorm-2.png){#fig-pnorm-2 width=672}\n:::\n\n::: {.cell-output-display}\n![The pnorm function takes a quantile (value on the x-axis) and returns the area under the curve to the left of that value.](norm_files/figure-html/fig-pnorm-3.png){#fig-pnorm-3 width=672}\n:::\n\n::: {.cell-output-display}\n![The pnorm function takes a quantile (value on the x-axis) and returns the area under the curve to the left of that value.](norm_files/figure-html/fig-pnorm-4.png){#fig-pnorm-4 width=672}\n:::\n:::\n\n\nThe option `lower.tail = TRUE` tells R to use the area to the *left* of the given\npoint — the default. To get the area to the **right** instead, either switch to\n`lower.tail = FALSE` or subtract from 1:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(1, lower.tail = FALSE)   # area to the RIGHT of 1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1586553\n```\n\n\n:::\n\n```{.r .cell-code}\n1 - pnorm(1)                   # exactly the same thing\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1586553\n```\n\n\n:::\n:::\n\n\n\n\n## dnorm\n\n`dnorm` gives the **height** of the bell curve at a value — the probability\n*density*. The curve is tallest at the mean and falls off symmetrically on either\nside. Unlike `pnorm`, the result is not a probability you can read as a percentage;\nit's the height of the curve, used mainly for *drawing* the distribution or in\nlikelihood calculations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndnorm(0)    # the peak of the standard normal\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3989423\n```\n\n\n:::\n\n```{.r .cell-code}\ndnorm(1)    # lower, one SD out...\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2419707\n```\n\n\n:::\n\n```{.r .cell-code}\ndnorm(-1)   # ...and the same height on the other side, by symmetry\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2419707\n```\n\n\n:::\n:::\n\n\nThe figures below mark each of these heights on the curve.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The `dnorm` function returns the height of the normal distribution at a given point.](norm_files/figure-html/fig-dnorm-1.png){#fig-dnorm-1 width=672}\n:::\n\n::: {.cell-output-display}\n![The `dnorm` function returns the height of the normal distribution at a given point.](norm_files/figure-html/fig-dnorm-2.png){#fig-dnorm-2 width=672}\n:::\n\n::: {.cell-output-display}\n![The `dnorm` function returns the height of the normal distribution at a given point.](norm_files/figure-html/fig-dnorm-3.png){#fig-dnorm-3 width=672}\n:::\n:::\n\n\n## qnorm\n\n`qnorm` runs `pnorm` in reverse: hand it a probability and it returns the value\nwith that much area to its left. Since `pnorm(1)` is about 0.84, `qnorm(0.84)` is\nabout 1 — the two functions undo each other. This is how you find **percentiles**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(0.5)     # the median: half the area lies to its left\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nqnorm(0.25)    # the first quartile\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.6744898\n```\n\n\n:::\n\n```{.r .cell-code}\nqnorm(0.975)   # the value cutting off the top 2.5% — the famous 1.96\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.959964\n```\n\n\n:::\n:::\n\n\nThe figures below show several quantiles as shaded areas.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The qnorm function is the inverse of the pnorm function in that it takes a probability and gives the quantile.](norm_files/figure-html/fig-qnorm-1.png){#fig-qnorm-1 width=672}\n:::\n\n::: {.cell-output-display}\n![The qnorm function is the inverse of the pnorm function in that it takes a probability and gives the quantile.](norm_files/figure-html/fig-qnorm-2.png){#fig-qnorm-2 width=672}\n:::\n\n::: {.cell-output-display}\n![The qnorm function is the inverse of the pnorm function in that it takes a probability and gives the quantile.](norm_files/figure-html/fig-qnorm-3.png){#fig-qnorm-3 width=672}\n:::\n\n::: {.cell-output-display}\n![The qnorm function is the inverse of the pnorm function in that it takes a probability and gives the quantile.](norm_files/figure-html/fig-qnorm-4.png){#fig-qnorm-4 width=672}\n:::\n\n::: {.cell-output-display}\n![The qnorm function is the inverse of the pnorm function in that it takes a probability and gives the quantile.](norm_files/figure-html/fig-qnorm-5.png){#fig-qnorm-5 width=672}\n:::\n:::\n\n\n\n## rnorm\n\n`rnorm` draws random samples from the distribution — the workhorse for *simulating*\ndata (we leaned on it heavily in the t-distribution chapter). Give it a count `n`\nand it hands back that many random values:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrnorm(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.0235803 -0.6010343  0.2398582 -0.3250300 -1.8590370\n```\n\n\n:::\n:::\n\n\nRun that again and you'll get five *different* numbers. To make a simulation\nreproducible — so you and a reader see the same \"random\" draws — set a seed first:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\nrnorm(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  1.3709584 -0.5646982  0.3631284  0.6328626  0.4042683\n```\n\n\n:::\n:::\n\n\nAnd just like the other functions, `mean` and `sd` shift and scale the draws:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrnorm(5, mean = 100, sd = 15)   # e.g. five simulated IQ scores\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  98.40813 122.67283  98.58011 130.27636  99.05929\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(r1)\n```\n\n::: {.cell-output-display}\n![The rnorm function takes a number of samples and returns a vector of random numbers from the normal distribution (with mean=0, sd=1 as defaults)](norm_files/figure-html/fig-rnorm-1.png){#fig-rnorm width=672}\n:::\n:::\n\n\n\n## Worked example: IQ scores\n\nThe normal distribution (also called the Gaussian distribution) is defined by two\nnumbers: the **mean** (µ), which sets the centre, and the **standard deviation**\n(σ), which sets the spread. IQ scores are deliberately built to be normal with a\n**mean of 100** and a **standard deviation of 15**, which makes them a perfect\nplayground for the four functions.\n\nA handy rule of thumb — the \"68–95–99.7 rule\" — says about 68% of values fall\nwithin one standard deviation of the mean (here, 85 to 115) and about 95% within\ntwo (70 to 130). Let's check the 68% with `pnorm`. The area *between* 85 and 115 is\nthe area below 115 minus the area below 85:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(115, mean = 100, sd = 15) - pnorm(85, mean = 100, sd = 15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6826895\n```\n\n\n:::\n:::\n\n\nAbout 0.68 — exactly what the rule promises. Notice the pattern: a \"between\"\nquestion becomes one `pnorm` minus another.\n\n## Exercises\n\nUse the IQ distribution (mean 100, sd 15) for each. Each solution names *which* of\nthe four functions fits the question — that choice is the real skill.\n\n1. **Top 10%.** Which IQ score marks the 90th percentile — the cutoff above which\n   only the top 10% fall?\n\n   ::: {.callout-note collapse=\"true\"}\n   ## Solution\n\n   ::: {.cell}\n   \n   ```{.r .cell-code}\n   qnorm(0.9, mean = 100, sd = 15)\n   ```\n   \n   ::: {.cell-output .cell-output-stdout}\n   \n   ```\n   [1] 119.2233\n   ```\n   \n   \n   :::\n   :::\n\n   We want a *value* from a *probability*, so this is a `qnorm` job. About 119.\n   :::\n\n2. **Above 130.** What fraction of people have an IQ above 130 (two standard\n   deviations up)?\n\n   ::: {.callout-note collapse=\"true\"}\n   ## Solution\n\n   ::: {.cell}\n   \n   ```{.r .cell-code}\n   1 - pnorm(130, mean = 100, sd = 15)\n   ```\n   \n   ::: {.cell-output .cell-output-stdout}\n   \n   ```\n   [1] 0.02275013\n   ```\n   \n   \n   :::\n   \n   ```{.r .cell-code}\n   # or, equivalently:\n   pnorm(130, mean = 100, sd = 15, lower.tail = FALSE)\n   ```\n   \n   ::: {.cell-output .cell-output-stdout}\n   \n   ```\n   [1] 0.02275013\n   ```\n   \n   \n   :::\n   :::\n\n   About 2.3% — consistent with the 95% rule leaving roughly 2.5% in each tail.\n   :::\n\n3. **Below 70.** What fraction have an IQ below 70?\n\n   ::: {.callout-note collapse=\"true\"}\n   ## Solution\n\n   ::: {.cell}\n   \n   ```{.r .cell-code}\n   pnorm(70, mean = 100, sd = 15)\n   ```\n   \n   ::: {.cell-output .cell-output-stdout}\n   \n   ```\n   [1] 0.02275013\n   ```\n   \n   \n   :::\n   :::\n\n   Also about 2.3%. The curve is symmetric, so the lower tail past 70 mirrors the\n   upper tail past 130.\n   :::\n\n4. **Simulate a classroom.** Draw 30 random IQ scores and count how many land above\n   115. (Set a seed so your answer is reproducible.)\n\n   ::: {.callout-note collapse=\"true\"}\n   ## Solution\n\n   ::: {.cell}\n   \n   ```{.r .cell-code}\n   set.seed(1)\n   scores <- rnorm(30, mean = 100, sd = 15)\n   sum(scores > 115)\n   ```\n   \n   ::: {.cell-output .cell-output-stdout}\n   \n   ```\n   [1] 3\n   ```\n   \n   \n   :::\n   :::\n\n   Theory predicts about 16% above 115 — roughly 5 of 30 — but any single small\n   sample wobbles around that. Re-run with a different seed to feel the sampling\n   variability for yourself.\n   :::\n\n## Summary\n\nYou now have the four-function toolkit for the normal distribution — and, thanks to\nR's naming rule, the blueprint for every other distribution too:\n\n- `pnorm(x)` — area to the **left** of `x` (a probability). Use `lower.tail = FALSE`\n  or `1 - pnorm(x)` for the right tail, and one `pnorm` minus another for a range.\n- `dnorm(x)` — the **height** of the curve at `x` (a density).\n- `qnorm(p)` — the **value** at probability `p` (the inverse of `pnorm`); your tool\n  for percentiles.\n- `rnorm(n)` — `n` random **draws**; pair it with `set.seed()` for reproducible\n  simulations.\n\nKeep the pictures in mind: `pnorm` is an area, `dnorm` is a height, `qnorm` reads\nthe area axis backwards to a value, and `rnorm` scatters points along the curve.\n\n    \n",
    "supporting": [
      "norm_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}