project:
  type: book


author:
  - name: Sean Davis
    url: https://seandavi.github.io/
    affiliation: University of Colorado<br/>Anschutz School of Medicine
    affiliation-url: https://medschool.cuanschutz.edu/
    email: seandavi@gmail.com
citation:
  url: https://seandavi.github.io/RBiocBook 
date: "today"
description: |
  A collection of chapters more than a book, but....
execute:
  freeze: auto

website:
  google-analytics: "UA-93043521-1"
book:
  title: "The RBioc Book"
  date: "today"
  search: true
  repo-url: https://github.com/seandavi/RBiocBook
  url: https://seandavi.github.io/RBiocBook
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  page-navigation: true

  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
        - intro.qmd
        - r_intro_mechanics.qmd
        - r_basics.qmd
        - packages_and_dice.qmd
    - part: data_structures_overview.qmd
      chapters:
        - vectors.qmd
        - matrices.qmd
        - dataframes_intro.qmd
        - factors.qmd

    - part: eda_overview.qmd
      chapters:
        - dplyr_intro_msleep.qmd
        - eda_and_univariate_brfss.qmd

    - part: Statistics and Machine Learning
      chapters:
        #- working_with_distributions.qmd
        - norm.qmd
        - t-stats-and-tests.qmd
        - kmeans.qmd
        - ml_practical.qmd

    - part: "Bioconductor"
      chapters:
        - geoquery.qmd
        - bioc-summarizedexperiment.qmd
        - eda_with_pca.qmd
    - references.qmd

  appendices:
    - appendix.qmd
    - additional_resources.qmd
    #- part: "Bioconductor"
      #chapters:
        #- bioconductor_intro.qmd
        #- bioconductor_packages.qmd
  page-footer:
    center: 
      - text: "License"
        href: license.qmd

bibliography: bibliography.bib

format:

  html:
    code-tools:
      source: repo
    fig-cap-location: margin
    tbl-cap-location: margin
    code-copy: true
    theme:
      light: [simplex, style/custom.scss]
    fontsize: "15px"
    linestretch: 1.6
    mainfont: "Roboto"
      #monofont: "Fira Mono"
    smooth-scroll: true
    toc-depth: 3
    code-link: true
    highlight-style: printing
    code-block-bg: true
    code-overflow: wrap
    reference-location: margin
    mermaid:
      theme: neutral
  titlepage-pdf:
    titlepage: academic
    linkcolor: blue
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    fontfamily: libertinus
    tbl-cap-location: margin
    fig-cap-location: margin
    lot: true
    lof: true
    # insert index entries: Markdown\index{Markdown} allows you to write ...
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \usepackage{hyperref}
        \makeindex
    include-after-body: 
      text: |
        \printindex
  epub:
    cover-image: images/cover.png 
