<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Sean Davis">
<meta name="dcterms.date" content="2024-06-01">
<meta name="description" content="A collection of chapters more than a book, but….">
<title>39&nbsp; Single-cell RNA-seq analysis – The RBioc Book</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../single_cell/multiome.html" rel="next">
<link href="../single_cell/concepts.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-709e903f7486fc15c5f7f9cf283d35df.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-709e903f7486fc15c5f7f9cf283d35df.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-709e903f7486fc15c5f7f9cf283d35df.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-89274b6a7b026c87465810c35957e583.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-6dd28c7963e21d618ae16e7ac0413509.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-89274b6a7b026c87465810c35957e583.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-KLLV1GCF4E"></script><script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-KLLV1GCF4E', { 'anonymize_ip': true});
</script><style>html{ scroll-behavior: smooth; }</style>
<script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating nav-fixed slimcontent quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">The RBioc Book</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
</div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools tools-wide">
    <a href="https://github.com/seandavi/RBiocBook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
<li>
            <a class="dropdown-item quarto-navbar-tools-item" href="../The-RBioc-Book.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="../The-RBioc-Book.epub">
              <i class="bi bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
</div>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-1" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-1">
<li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://twitter.com/intent/tweet?url=%7Curl%7C">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://www.facebook.com/sharer/sharer.php?u=%7Curl%7C">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
      </ul>
</div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../bioc-summarizedexperiment.html">Bioconductor</a></li><li class="breadcrumb-item"><a href="../single_cell/setup.html"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Single-cell RNA-seq analysis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Introduction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">About R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intro_to_rstudio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../r_intro_mechanics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">R mechanics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sampling_and_functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Random sampling and writing functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../packages_and_simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Packages, simulation, and the law of large numbers</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../rproj_and_save_load.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Organizing, saving, and loading your work</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../literate_programming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Literate programming with Quarto</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reading_and_writing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Reading and writing data files</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">A Biology Primer</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../biology_primer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">A primer on biological assays</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../data_structures_overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R Data Structures</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vectors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Vectors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../matrices.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Matrices</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lists.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Lists: a catch-all container</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../dataframes_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Data Frames</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../factors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Factors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../control_statements.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Control statements</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../eda_overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exploratory data analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../dplyr_intro_msleep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Introduction to dplyr: mammal sleep dataset</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../eda_and_univariate_brfss.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Case Study: Behavioral Risk Factor Surveillance System</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ggplot2/intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Exploring data with ggplot2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../comparison_options.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Base R versus the tidyverse</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../visualization_guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">A self-guided tour of data visualization in R</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../norm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Working with distribution functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../t-stats-and-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">The t-statistic and t-distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../kmeans.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">K-means clustering</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Machine Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../machine_learning/intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Introduction to machine learning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../machine_learning/models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Supervised Learning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../machine_learning/mlr3verse_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">The mlr3verse framework</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../machine_learning/ml_cancer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Worked example: classifying cancer types from gene expression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../machine_learning/ml_methylation_age.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Worked example: predicting age from DNA methylation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../machine_learning/ml_expression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Worked example: predicting gene expression from histone marks</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Bioconductor</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../bioc-summarizedexperiment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Working with a SummarizedExperiment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../geoquery.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Accessing public omics data with GEOquery</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../bioc-se-building.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Building and sharing a SummarizedExperiment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../310_microbiome.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Analyzing microbiome data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../genomic_ranges.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Genomic ranges and features</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../genomic_ranges_chipseq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Genomic ranges with real ChIP-seq peaks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ranges_exercises.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Ranges Exercises</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../atac-seq/atac-seq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Genomic ranges and ATAC-seq</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../single_cell/concepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">How single-cell analysis works</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../single_cell/setup.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Single-cell RNA-seq analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../single_cell/multiome.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Integrating single-cell ATAC and RNA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../single_cell/atac_rna_label_transfer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Label transfer: annotating scATAC-seq from an scRNA-seq reference</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contributors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Contributors &amp; acknowledgments</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../git_and_github.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Git and GitHub</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../additional_resources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Further reading, cheat sheets, and datasets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ai_tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">AI Tools for Enhanced Learning and Productivity in Bioinformatics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../matrix_exercises.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Matrix Exercises</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#what-youll-learn" id="toc-what-youll-learn" class="nav-link active" data-scroll-target="#what-youll-learn"><span class="header-section-number">39.1</span> What you’ll learn</a></li>
  <li>
<a href="#setup-and-data-loading" id="toc-setup-and-data-loading" class="nav-link" data-scroll-target="#setup-and-data-loading"><span class="header-section-number">39.2</span> Setup and data loading</a>
  <ul class="collapse">
<li><a href="#loading-the-libraries" id="toc-loading-the-libraries" class="nav-link" data-scroll-target="#loading-the-libraries"><span class="header-section-number">39.2.1</span> Loading the libraries</a></li>
  <li><a href="#exploring-available-datasets" id="toc-exploring-available-datasets" class="nav-link" data-scroll-target="#exploring-available-datasets"><span class="header-section-number">39.2.2</span> Exploring available datasets</a></li>
  </ul>
</li>
  <li>
<a href="#dimensionality-reduction" id="toc-dimensionality-reduction" class="nav-link" data-scroll-target="#dimensionality-reduction"><span class="header-section-number">39.3</span> Dimensionality reduction</a>
  <ul class="collapse">
<li><a href="#feature-selection-identifying-highly-variable-genes" id="toc-feature-selection-identifying-highly-variable-genes" class="nav-link" data-scroll-target="#feature-selection-identifying-highly-variable-genes"><span class="header-section-number">39.3.1</span> Feature selection: identifying highly variable genes</a></li>
  <li><a href="#non-linear-dimensionality-reduction-with-umap" id="toc-non-linear-dimensionality-reduction-with-umap" class="nav-link" data-scroll-target="#non-linear-dimensionality-reduction-with-umap"><span class="header-section-number">39.3.2</span> Non-linear dimensionality reduction with UMAP</a></li>
  <li><a href="#visualizing-cell-types-and-clusters" id="toc-visualizing-cell-types-and-clusters" class="nav-link" data-scroll-target="#visualizing-cell-types-and-clusters"><span class="header-section-number">39.3.3</span> Visualizing cell types and clusters</a></li>
  <li><a href="#t-sne-vs-umap" id="toc-t-sne-vs-umap" class="nav-link" data-scroll-target="#t-sne-vs-umap"><span class="header-section-number">39.3.4</span> t-SNE vs UMAP</a></li>
  </ul>
</li>
  <li>
<a href="#finding-marker-genes" id="toc-finding-marker-genes" class="nav-link" data-scroll-target="#finding-marker-genes"><span class="header-section-number">39.4</span> Finding marker genes</a>
  <ul class="collapse">
<li><a href="#markers-for-the-clusters-you-discovered" id="toc-markers-for-the-clusters-you-discovered" class="nav-link" data-scroll-target="#markers-for-the-clusters-you-discovered"><span class="header-section-number">39.4.1</span> Markers for the clusters you discovered</a></li>
  </ul>
</li>
  <li>
<a href="#from-clusters-to-cell-types-annotation" id="toc-from-clusters-to-cell-types-annotation" class="nav-link" data-scroll-target="#from-clusters-to-cell-types-annotation"><span class="header-section-number">39.5</span> From clusters to cell types: annotation</a>
  <ul class="collapse">
<li><a href="#painting-marker-genes-onto-the-map" id="toc-painting-marker-genes-onto-the-map" class="nav-link" data-scroll-target="#painting-marker-genes-onto-the-map"><span class="header-section-number">39.5.1</span> Painting marker genes onto the map</a></li>
  <li><a href="#marker-lists-are-gene-sets" id="toc-marker-lists-are-gene-sets" class="nav-link" data-scroll-target="#marker-lists-are-gene-sets"><span class="header-section-number">39.5.2</span> Marker lists are gene sets</a></li>
  </ul>
</li>
  <li><a href="#interactive-visualization-with-isee" id="toc-interactive-visualization-with-isee" class="nav-link" data-scroll-target="#interactive-visualization-with-isee"><span class="header-section-number">39.6</span> Interactive visualization with iSEE</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">39.7</span> Exercises</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">39.8</span> Summary</a></li>
  <li>
<a href="#bonus-working-with-10x-genomics-data" id="toc-bonus-working-with-10x-genomics-data" class="nav-link" data-scroll-target="#bonus-working-with-10x-genomics-data"><span class="header-section-number">39.9</span> Bonus: working with 10x Genomics data</a>
  <ul class="collapse">
<li><a href="#understanding-10x-genomics-output-formats" id="toc-understanding-10x-genomics-output-formats" class="nav-link" data-scroll-target="#understanding-10x-genomics-output-formats"><span class="header-section-number">39.9.1</span> Understanding 10x Genomics output formats</a></li>
  <li><a href="#loading-10x-data-from-matrix-market-files" id="toc-loading-10x-data-from-matrix-market-files" class="nav-link" data-scroll-target="#loading-10x-data-from-matrix-market-files"><span class="header-section-number">39.9.2</span> Loading 10x data from Matrix Market files</a></li>
  <li><a href="#loading-from-hdf5-files" id="toc-loading-from-hdf5-files" class="nav-link" data-scroll-target="#loading-from-hdf5-files"><span class="header-section-number">39.9.3</span> Loading from HDF5 files</a></li>
  <li><a href="#essential-quality-control-after-loading-raw-data" id="toc-essential-quality-control-after-loading-raw-data" class="nav-link" data-scroll-target="#essential-quality-control-after-loading-raw-data"><span class="header-section-number">39.9.4</span> Essential quality control after loading raw data</a></li>
  <li><a href="#filtering-low-quality-cells-and-genes" id="toc-filtering-low-quality-cells-and-genes" class="nav-link" data-scroll-target="#filtering-low-quality-cells-and-genes"><span class="header-section-number">39.9.5</span> Filtering low-quality cells and genes</a></li>
  </ul>
</li>
  <li><a href="#further-reading-and-resources" id="toc-further-reading-and-resources" class="nav-link" data-scroll-target="#further-reading-and-resources"><span class="header-section-number">39.10</span> Further reading and resources</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/seandavi/RBiocBook/edit/main/single_cell/setup.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/seandavi/RBiocBook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li><li><a href="https://github.com/seandavi/RBiocBook/blob/main/single_cell/setup.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../bioc-summarizedexperiment.html">Bioconductor</a></li><li class="breadcrumb-item"><a href="../single_cell/setup.html"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Single-cell RNA-seq analysis</span></a></li></ol></nav><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">
<span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Single-cell RNA-seq analysis</span>
</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source" data-quarto-source-url="https://github.com/seandavi/RBiocBook/blob/main/single_cell/setup.qmd"><i class="bi"></i> Code</button></div></div>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author"><a href="https://seandavi.github.io/">Sean Davis</a> <a href="mailto:seandavi@gmail.com" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            <a href="https://medschool.cuanschutz.edu/">
            University of Colorado<br>Anschutz School of Medicine
            </a>
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 1, 2024</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">June 22, 2026</p>
    </div>
  </div>
    
  </div>
  


</header><p>Bulk RNA-seq hands you one expression profile per sample — the average over every cell in the tube. But a tissue is not one cell type. Mash a piece of brain into a single average and you blur neurons, glia, and blood vessels into one indistinct smear. Single-cell RNA sequencing (scRNA-seq) measures gene expression one cell at a time, so instead of an average you get a catalog: which cell types are present, how many of each, and what makes each one distinct. That shift is what lets you discover a rare cell population, trace a developmental trajectory, or spot the cells that change in disease.</p>
<p>In this chapter you’ll take a published mouse-brain dataset from raw counts to a labeled map of cell types, using the Bioconductor single-cell toolkit. Along the way you’ll meet the standard workflow — load, normalize, pick informative genes, reduce dimensions, cluster, and find marker genes — that underlies essentially every scRNA-seq analysis.</p>
<p>The data container we’ll use, the <code>SingleCellExperiment</code>, is built directly on the <code>SummarizedExperiment</code> class from the <a href="../bioc-summarizedexperiment.html">SummarizedExperiment chapter</a>. If that chapter’s three-linked-sheets picture (an assay matrix flanked by aligned row and column metadata) isn’t fresh, skim it first — everything here assumes it.</p>
<section id="what-youll-learn" class="level2" data-number="39.1"><h2 data-number="39.1" class="anchored" data-anchor-id="what-youll-learn">
<span class="header-section-number">39.1</span> What you’ll learn</h2>
<p>By the end of this chapter you will be able to:</p>
<ul>
<li>Load a curated scRNA-seq dataset as a <code>SingleCellExperiment</code> object.</li>
<li>Log-normalize raw counts to correct for differences in sequencing depth.</li>
<li>Select the highly variable genes that carry the biological signal.</li>
<li>Run PCA and then UMAP to reduce the data to a 2D map, and see how UMAP compares to t-SNE.</li>
<li>Cluster cells into groups and inspect how those groups line up with known cell types.</li>
<li>Find and visualize the marker genes that define each cluster.</li>
<li>Paint marker genes onto a UMAP to see <em>where</em> each cell type lives.</li>
<li>Recognize cell-type annotation as a form of gene-set scoring.</li>
</ul></section><section id="setup-and-data-loading" class="level2 page-columns page-full" data-number="39.2"><h2 data-number="39.2" class="anchored" data-anchor-id="setup-and-data-loading">
<span class="header-section-number">39.2</span> Setup and data loading</h2>
<section id="loading-the-libraries" class="level3" data-number="39.2.1"><h3 data-number="39.2.1" class="anchored" data-anchor-id="loading-the-libraries">
<span class="header-section-number">39.2.1</span> Loading the libraries</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Load essential libraries for single-cell RNA-seq analysis</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">scRNAseq</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/libscran/scrapper">scrapper</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://bioconductor.org/packages/scater/">scater</a></span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We start by loading three essential R packages for single-cell analysis:</p>
<ul>
<li>
<strong>scRNAseq</strong>: Provides access to curated single-cell RNA-seq datasets, making it easy to practice analysis techniques on real data. At the time of writing, it includes more than 50 datasets covering various tissues, organisms, and experimental conditions. See <span class="citation" data-cites="risso2024scRNAseq">Risso and Cole (<a href="../references.html#ref-risso2024scRNAseq" role="doc-biblioref">2024</a>)</span>
</li>
<li>
<strong>scrapper</strong>: Provides fast, modern implementations of the core single-cell numerics — normalization, feature selection, PCA, clustering, and marker detection. It is the successor to the older <code>scran</code>/<code>scuttle</code> stack: the same algorithms, re-implemented in C++ for speed, with a consistent functional interface. For most steps we use its <code>.se</code> helpers, which read from and write to a <code>SingleCellExperiment</code> so the familiar object stays at the centre of the workflow; for marker detection we call the matrix-level <code><a href="https://rdrr.io/pkg/scrapper/man/scoreMarkers.html">scoreMarkers()</a></code> directly. See <span class="citation" data-cites="lun2016">Lun et al. (<a href="../references.html#ref-lun2016" role="doc-biblioref">2016</a>)</span>.</li>
<li>
<strong>scater</strong>: Offers tools for visualization and exploratory data analysis. We use it here purely for plotting (<code>plotReducedDim</code>, <code>plotHeatmap</code>); scrapper does the numerical heavy lifting. See <span class="citation" data-cites="McCarthy2017scater">McCarthy et al. (<a href="../references.html#ref-McCarthy2017scater" role="doc-biblioref">2017</a>)</span>.</li>
</ul>
<p>Single-cell data has unique characteristics (sparsity, high dimensionality, technical noise) that require specialized tools. These packages form the backbone of the Bioconductor single-cell analysis ecosystem and provide methods that account for the specific challenges of single-cell data.</p>
</section><section id="exploring-available-datasets" class="level3 page-columns page-full" data-number="39.2.2"><h3 data-number="39.2.2" class="anchored" data-anchor-id="exploring-available-datasets">
<span class="header-section-number">39.2.2</span> Exploring available datasets</h3>
<p>We are going to use the <code>scRNAseq</code> package to access a curated collection of single-cell datasets. This package provides a convenient way to load and explore publicly available datasets that have been processed and annotated.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">datasets</span> <span class="op">&lt;-</span> <span class="fu">scRNAseq</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/scRNAseq/man/surveyDatasets.html">surveyDatasets</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The <code><a href="https://rdrr.io/pkg/scRNAseq/man/surveyDatasets.html">surveyDatasets()</a></code> function queries the scRNAseq package database to show all available datasets. This creates a simple table of publicly available single-cell datasets that have been processed and made easily accessible.</p>
<p>Having access to well-curated datasets is useful for learning and benchmarking. These datasets come from published studies and represent different tissues, conditions, and experimental designs, allowing us to practice on real biological data without having to process raw sequencing files.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>DataFrame with 10 rows and 15 columns
                     name     version        path                 object
              &lt;character&gt; &lt;character&gt; &lt;character&gt;            &lt;character&gt;
1       aztekin-tail-2019  2023-12-14          NA single_cell_experiment
2  splicing-demonstrati..  2023-12-20          NA single_cell_experiment
3      marques-brain-2016  2023-12-19          NA single_cell_experiment
4   grun-bone_marrow-2016  2023-12-14          NA single_cell_experiment
5         giladi-hsc-2018  2023-12-21      crispr single_cell_experiment
6         giladi-hsc-2018  2023-12-21         rna single_cell_experiment
7     macosko-retina-2015  2023-12-19          NA single_cell_experiment
8        messmer-esc-2019  2023-12-19          NA single_cell_experiment
9  ernst-spermatogenesi..  2023-12-21  cellranger single_cell_experiment
10 ernst-spermatogenesi..  2023-12-21  emptydrops single_cell_experiment
                    title            description taxonomy_id   genome      rows
              &lt;character&gt;            &lt;character&gt;      &lt;List&gt;   &lt;List&gt; &lt;integer&gt;
1  Identification of a .. Identification of a ..        8355 Xenla9.1     31535
2  [reprocessed, subset.. [reprocessed, subset..       10090   GRCm38     54448
3  Oligodendrocyte hete.. Oligodendrocyte hete..       10090   GRCm38     23556
4  De Novo Prediction o.. De Novo Prediction o..       10090   GRCm38     23536
5  Single-cell characte.. Single-cell characte..       10090  MGSCv37        30
6  Single-cell characte.. Single-cell characte..       10090  MGSCv37     27389
7  Highly Parallel Geno.. Highly Parallel Geno..       10090   GRCm38     24658
8  Transcriptional Hete.. Transcriptional Hete..        9606   GRCh38     58302
9  Staged developmental.. Staged developmental..       10090   GRCm38     33226
10 Staged developmental.. Staged developmental..       10090   GRCm38     32105
     columns            assays                               column_annotations
   &lt;integer&gt;            &lt;List&gt;                                           &lt;List&gt;
1      13199            counts sample,DevelopmentalStage,DaysPostAmputation,...
2       2325 spliced,unspliced                                         celltype
3       5069            counts           source_name,age,inferred cell type,...
4       1915            counts                                  sample,protocol
5      24070            counts                              amplification.batch
6      81408            counts               Amp_batch_ID,Seq_batch_ID,tier,...
7      49300            counts                                          cluster
8       1344            counts    Source Name,phenotype,single cell quality,...
9      53510            counts                       Sample,Barcode,Library,...
10     68937            counts                       Sample,Barcode,Library,...
   reduced_dimensions alternative_experiments
               &lt;List&gt;                  &lt;List&gt;
1                UMAP                        
2                                            
3                                            
4                                            
5                                            
6                                            
7                                            
8                                        ERCC
9                                            
10                                           
                                                                    sources
                                                       &lt;SplitDataFrameList&gt;
1                            ArrayExpress:E-MTAB-7716:NA,PubMed:31097661:NA
2                      GEO:GSE109033:NA,GEO:GSM2928341:NA,SRA:SRR6459157:NA
3                                        GEO:GSE75330:NA,PubMed:27284195:NA
4                                        GEO:GSE76983:NA,PubMed:27345837:NA
5                                        PubMed:29915358:NA,GEO:GSE11349:NA
6                                        PubMed:29915358:NA,GEO:GSE92575:NA
7  GEO:GSE63472:NA,PubMed:26000488:NA,URL:http://mccarrolllab...:2024-02-23
8                            PubMed:30673604:NA,ArrayExpress:E-MTAB-6819:NA
9                            ArrayExpress:E-MTAB-6946:NA,PubMed:30890697:NA
10                           ArrayExpress:E-MTAB-6946:NA,PubMed:30890697:NA</code></pre>
</div>
</div>
<p>Each row represents a different study. The ‘columns’ field shows the number of cells, while ‘rows’ shows the number of genes. This helps you choose datasets appropriate for your computational resources and analysis goals. This little lightweight database is not the richest way to explore datasets, but it is a good starting point. In this tutorial, we will use the <code>ZeiselBrainData</code> dataset, which contains single-cell RNA-seq data from mouse brain tissue (<span class="citation" data-cites="zeiselCellTypesMouse2015">Zeisel et al. (<a href="../references.html#ref-zeiselCellTypesMouse2015" role="doc-biblioref">2015</a>)</span>).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Abstract: the Zeisel brain dataset
</div>
</div>
<div class="callout-body-container callout-body">
<p>The mammalian cerebral cortex supports cognitive functions such as sensorimotor integration, memory, and social behaviors. Normal brain function relies on a diverse set of differentiated cell types, including neurons, glia, and vasculature. Here, we have used large-scale single-cell RNA sequencing (RNA-seq) to classify cells in the mouse somatosensory cortex and hippocampal CA1 region. We found 47 molecularly distinct subclasses, comprising all known major cell types in the cortex. We identified numerous marker genes, which allowed alignment with known cell types, morphology, and location. We found a layer I interneuron expressing Pax6 and a distinct postmitotic oligodendrocyte subclass marked by Itpr2. Across the diversity of cortical cell types, transcription factors formed a complex, layered regulatory code, suggesting a mechanism for the maintenance of adult cell type identity.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sce</span> <span class="op">&lt;-</span> <span class="fu">scRNAseq</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/scRNAseq/man/ZeiselBrainData.html">ZeiselBrainData</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>What is the <code>sce</code> object? It is a <code>SingleCellExperiment</code> object, a data structure designed specifically for single-cell RNA-seq data. It is built directly on top of the <code>SummarizedExperiment</code> class you met in the <a href="../bioc-summarizedexperiment.html">SummarizedExperiment chapter</a> (see <a href="#fig-scRNAseq-sce" class="quarto-xref">Figure&nbsp;<span>39.1</span></a>), so the same mental model applies: an assay matrix of counts, with aligned metadata about the features (genes) down the rows and the cells across the columns. A <code>SingleCellExperiment</code> simply adds a few single-cell-specific extras on top, most importantly a slot for dimensionality reductions like PCA and UMAP.</p>
<div id="fig-scRNAseq-sce" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure page-columns page-full"><div aria-describedby="fig-scRNAseq-sce-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41592-019-0654-x/MediaObjects/41592_2019_654_Fig2_HTML.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;39.1: The SingleCellExperiment object."><img src="https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41592-019-0654-x/MediaObjects/41592_2019_654_Fig2_HTML.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></a>
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-scRNAseq-sce-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;39.1: The SingleCellExperiment object.
</figcaption></figure>
</div>
<p>Printing the <code>sce</code> object gives us a summary of the dataset:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sce</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>class: SingleCellExperiment 
dim: 20006 3005 
metadata(0):
assays(1): counts
rownames(20006): Tspan12 Tshz1 ... mt-Rnr1 mt-Nd4l
rowData names(1): featureType
colnames(3005): 1772071015_C02 1772071017_G12 ... 1772066098_A12
  1772058148_F03
colData names(9): tissue group # ... level1class level2class
reducedDimNames(0):
mainExpName: gene
altExpNames(2): repeat ERCC</code></pre>
</div>
</div>
<p>The <code>SingleCellExperiment</code> object contains:</p>
<ul>
<li>
<strong>Assays</strong>: The main data matrix (counts) and any additional matrices (e.g., normalized counts).</li>
<li>
<strong>Row metadata</strong>: Information about genes (e.g., gene names, IDs).</li>
<li>
<strong>Column metadata</strong>: Information about cells (e.g., cell barcodes, tissue type, experimental conditions).</li>
</ul>
<p>It <strong>can</strong> also contain additional information such as dimensionality reductions (e.g., PCA, UMAP), clustering results, and quality control metrics.</p>
<p>In fact, we are going to add some of this additional information in the next steps. First, we add a new assay with the log-normalized counts, which is a common preprocessing step in single-cell RNA-seq analysis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sce</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/scrapper/man/normalizeRnaCounts.se.html">normalizeRnaCounts.se</a></span><span class="op">(</span><span class="va">sce</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The <code><a href="https://rdrr.io/pkg/scrapper/man/normalizeRnaCounts.se.html">normalizeRnaCounts.se()</a></code> function performs log-normalization of the count data. It reads the <code>counts</code> assay, computes a size factor for each cell, and writes a new <code>logcounts</code> assay (and a <code>sizeFactor</code> column) back into the <code>sce</code> object — so afterwards <code>logcounts(sce)</code> holds the normalized values. Raw count data from scRNA-seq experiments contains technical variation due to differences in sequencing depth between cells. Some cells might have been sequenced more deeply than others, leading to higher total counts that don’t reflect true biological differences. Log-normalization addresses this by:</p>
<ol type="1">
<li>
<strong>Size factor normalization</strong>: Scaling each cell’s counts by a per-cell <em>size factor</em> that captures how deeply it was sequenced. <code><a href="https://rdrr.io/pkg/scrapper/man/normalizeRnaCounts.se.html">normalizeRnaCounts.se()</a></code> uses the simplest such factor — the cell’s total count (its <em>library size</em>), centered so the average factor across cells is 1 — and divides every gene’s count by it. More robust estimators exist; the <a href="../single_cell/concepts.html#sec-normalization">concepts chapter</a> explains the deconvolution refinement used when cells differ in composition.</li>
<li>
<strong>Log transformation</strong>: Taking log(count + 1) to stabilize variance and make the data more normally distributed</li>
</ol>
<p>For each gene g in cell i, the log-normalized expression becomes:</p>
<p><span class="math display">\[log_2\left(\frac{count_{g_i}}{{size factor}_{i}} + 1\right)\]</span></p>
<p>This log transformation is useful because the next steps in the downstream analyses (like clustering and dimensionality reduction) assume that the data is approximately normally distributed (or at least bell-shaped). Log-normalization helps achieve this by reducing the impact of outliers and making the data more suitable for PCA and visualization.</p>
</section></section><section id="dimensionality-reduction" class="level2 page-columns page-full" data-number="39.3"><h2 data-number="39.3" class="anchored" data-anchor-id="dimensionality-reduction">
<span class="header-section-number">39.3</span> Dimensionality reduction</h2>
<p>Single-cell datasets are extremely high-dimensional - typically containing 15,000-30,000 genes per cell. This creates several challenges: computational complexity, noise dominance, and visualization difficulties. Dimensionality reduction techniques help us identify the most informative patterns in the data while reducing noise and computational burden.</p>
<section id="feature-selection-identifying-highly-variable-genes" class="level3 page-columns page-full" data-number="39.3.1"><h3 data-number="39.3.1" class="anchored" data-anchor-id="feature-selection-identifying-highly-variable-genes">
<span class="header-section-number">39.3.1</span> Feature selection: identifying highly variable genes</h3>
<p>Before applying dimensionality reduction, we need to identify the most informative genes. Highly variable genes (HVGs) are those that show significant variation across cells, indicating they may be biologically relevant. These genes are often more informative for downstream analyses like clustering and visualization.</p>
<p>Not all genes are equally informative for distinguishing cell types. Genes that show little variation across cells (like housekeeping genes) don’t help us identify distinct cell populations. Highly variable genes are more likely to:</p>
<ul>
<li>Reflect biological differences between cell types</li>
<li>Capture developmental or activation states</li>
<li>Represent responses to environmental conditions</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sce</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/scrapper/man/chooseRnaHvgs.se.html">chooseRnaHvgs.se</a></span><span class="op">(</span><span class="va">sce</span>, top<span class="op">=</span><span class="fl">2000</span><span class="op">)</span></span>
<span><span class="va">top_var_genes</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">sce</span><span class="op">)</span><span class="op">[</span><span class="fu">rowData</span><span class="op">(</span><span class="va">sce</span><span class="op">)</span><span class="op">$</span><span class="va">hvg</span><span class="op">]</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The <code><a href="https://rdrr.io/pkg/scrapper/man/chooseRnaHvgs.se.html">chooseRnaHvgs.se()</a></code> function identifies the top 2000 highly variable genes based on their variance across cells. It models the mean–variance relationship internally, marks the chosen genes with a logical <code>hvg</code> column in <code>rowData(sce)</code>, and also stores the per-gene <code>means</code>, <code>variances</code>, and <code>fitted</code> trend values there. We pull the names of the selected genes into <code>top_var_genes</code> for the steps that need an explicit gene list. Choosing a subset of highly variable genes reduces the dimensionality of the dataset while retaining the most informative features for downstream analyses.</p>
<p>The algorithm models the relationship between gene expression mean and variance, then identifies genes that show more variation than expected based on their expression level. This accounts for the fact that highly expressed genes naturally show more variance.</p>
<div class="cell page-columns page-full">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Visualizing the highly variable genes. chooseRnaHvgs.se() already stored the</span></span>
<span><span class="co"># per-gene mean, variance, fitted trend, and hvg flag in rowData(sce).</span></span>
<span><span class="va">rd</span> <span class="op">&lt;-</span> <span class="fu">rowData</span><span class="op">(</span><span class="va">sce</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">rd</span><span class="op">$</span><span class="va">means</span>, <span class="va">rd</span><span class="op">$</span><span class="va">variances</span>, xlab<span class="op">=</span><span class="st">"Mean of log-expression"</span>,</span>
<span>    ylab<span class="op">=</span><span class="st">"Variance of log-expression"</span>, ylim<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">4</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co"># The fitted trend, drawn as a curve by ordering genes along the mean axis:</span></span>
<span><span class="va">o</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/order.html">order</a></span><span class="op">(</span><span class="va">rd</span><span class="op">$</span><span class="va">means</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span><span class="op">(</span><span class="va">rd</span><span class="op">$</span><span class="va">means</span><span class="op">[</span><span class="va">o</span><span class="op">]</span>, <span class="va">rd</span><span class="op">$</span><span class="va">fitted</span><span class="op">[</span><span class="va">o</span><span class="op">]</span>, col<span class="op">=</span><span class="st">"dodgerblue"</span>, lwd<span class="op">=</span><span class="fl">2</span><span class="op">)</span></span>
<span><span class="co"># Highlight the genes flagged as highly variable:</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/points.html">points</a></span><span class="op">(</span></span>
<span>    <span class="va">rd</span><span class="op">$</span><span class="va">means</span><span class="op">[</span><span class="va">rd</span><span class="op">$</span><span class="va">hvg</span><span class="op">]</span>, <span class="va">rd</span><span class="op">$</span><span class="va">variances</span><span class="op">[</span><span class="va">rd</span><span class="op">$</span><span class="va">hvg</span><span class="op">]</span>,</span>
<span>    col<span class="op">=</span><span class="st">"red"</span>, pch<span class="op">=</span><span class="fl">16</span>, cex<span class="op">=</span><span class="fl">0.5</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display page-columns page-full">
<div id="fig-scRNAseq-hvg" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full"><div aria-describedby="fig-scRNAseq-hvg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="setup_files/figure-html/fig-scRNAseq-hvg-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;39.2: A plot of the mean vs variance of log-expression for all the genes in the dataset, with the highly variable genes highlighted in red. Here, the x-axis represents the mean log-expression of each gene, and the y-axis represents the variance of log-expression. The blue curve represents the trend of variance as a function of mean expression, while the red points represent the highly variable genes."><img src="setup_files/figure-html/fig-scRNAseq-hvg-1.png" class="img-fluid figure-img" width="672"></a>
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-scRNAseq-hvg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;39.2: A plot of the mean vs variance of log-expression for all the genes in the dataset, with the highly variable genes highlighted in red. Here, the x-axis represents the mean log-expression of each gene, and the y-axis represents the variance of log-expression. The blue curve represents the trend of variance as a function of mean expression, while the red points represent the highly variable genes.
</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-scRNAseq-hvg" class="quarto-xref">Figure&nbsp;<span>39.2</span></a> shows the mean vs.&nbsp;variance of log-expression for all genes in the dataset, with highly variable genes highlighted in red. The blue curve represents the trend of variance as a function of mean expression, while the red points represent the highly variable genes.</p>
<p>We next proceed to calculating PCA using the subset of highly variable genes. PCA is a linear dimensionality reduction technique that finds the directions of maximum variance in the data. It’s computationally efficient and provides a good foundation for further analysis. The first few principal components capture the most important patterns of variation in the dataset.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Why PCA first?
</div>
</div>
<div class="callout-body-container callout-body">
<p>PCA is a widely <em>linear</em> dimensionality reduction technique that:</p>
<ul>
<li>Reduces dimensionality while preserving variance</li>
<li>Helps visualize high-dimensional data in 2D or 3D</li>
<li>Serves as a preprocessing step for other methods like t-SNE or UMAP</li>
<li>Is computationally efficient and easy to interpret</li>
</ul>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Perform PCA on the highly variable genes</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">100</span><span class="op">)</span> <span class="co"># See below.</span></span>
<span><span class="va">sce</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/scrapper/man/runPca.se.html">runPca.se</a></span><span class="op">(</span><span class="va">sce</span>, features<span class="op">=</span><span class="fu">rowData</span><span class="op">(</span><span class="va">sce</span><span class="op">)</span><span class="op">$</span><span class="va">hvg</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/SingleCellExperiment/man/reducedDims.html">reducedDimNames</a></span><span class="op">(</span><span class="va">sce</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "PCA"</code></pre>
</div>
</div>
<p>Note that we assign the output of <code><a href="https://rdrr.io/pkg/scrapper/man/runPca.se.html">runPca.se()</a></code> back to the <code>sce</code> object. The <code>features=rowData(sce)$hvg</code> argument restricts the PCA to the highly variable genes we flagged earlier, reducing the dimensionality of the dataset while retaining the most informative features. Because dimensionality reduction is a common step in single-cell RNA-seq analysis, the function stores the PCA results in the <code>reducedDims</code> slot of the <code>SingleCellExperiment</code> object (under the name <code>"PCA"</code>). This allows us to easily access and visualize the PCA coordinates later.</p>
</section><section id="non-linear-dimensionality-reduction-with-umap" class="level3" data-number="39.3.2"><h3 data-number="39.3.2" class="anchored" data-anchor-id="non-linear-dimensionality-reduction-with-umap">
<span class="header-section-number">39.3.2</span> Non-linear dimensionality reduction with UMAP</h3>
<p>After PCA, we apply a non-linear method to squeeze the data down to two dimensions we can actually look at. <strong>UMAP</strong> (Uniform Manifold Approximation and Projection) has become the field’s default for this step: it is fast, scales to very large datasets, and tends to preserve more of the <em>global</em> structure — the relative arrangement of clusters — than its predecessor, t-SNE. We’ll use it as our map for the rest of the chapter, and compare the two head-to-head in a moment.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Why UMAP after PCA — and why not cluster <em>on</em> it
</div>
</div>
<div class="callout-body-container callout-body">
<p>This is a two-step approach:</p>
<ol type="1">
<li>
<strong>PCA first</strong> compresses thousands of genes into a few dozen components, stripping noise while keeping the main axes of variation.</li>
<li>
<strong>UMAP second</strong> takes those components and lays them out in 2D so neighbouring cells sit together.</li>
</ol>
<p>One rule worth burning in: UMAP (like t-SNE) is a <strong>visualization</strong> of the data, not the data itself. It deliberately distorts distances to make a readable picture — so you <em>look</em> at it, but you do not <em>compute</em> on it. In particular, cluster on the PCA coordinates — the richer, denoised space — not on the 2-D embedding. Squeezing dozens of principal components down to two inevitably distorts distances and densities <span class="citation" data-cites="doi:10.1371/journal.pcbi.1011288">(<a href="../references.html#ref-doi:10.1371/journal.pcbi.1011288" role="doc-biblioref">Chari and Pachter 2023</a>)</span>, so clustering runs on the PCs while the embedding stays a picture — the convention OSCA, Seurat, and scanpy all follow <span class="citation" data-cites="doi:10.1038/s41592-019-0654-x">(<a href="../references.html#ref-doi:10.1038/s41592-019-0654-x" role="doc-biblioref">Amezquita et al. 2019</a>)</span>. The <a href="../single_cell/concepts.html">concepts chapter</a> unpacks the reasoning.</p>
</div>
</div>
<p>UMAP uses a random initialization, so its output changes from run to run. We call <code><a href="https://rdrr.io/r/base/Random.html">set.seed()</a></code> first so the figure is reproducible — you’ll see exactly the same map we do.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1234</span><span class="op">)</span></span>
<span><span class="va">sce</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/scrapper/man/runUmap.se.html">runUmap.se</a></span><span class="op">(</span><span class="va">sce</span>, reddim.type<span class="op">=</span><span class="st">"PCA"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The <code><a href="https://rdrr.io/pkg/scrapper/man/runUmap.se.html">runUmap.se()</a></code> function builds the embedding from the PCA results and stores it in the <code>reducedDims</code> slot (under <code>"UMAP"</code>). The <code>reddim.type="PCA"</code> argument tells it to start from the PCA coordinates rather than the raw genes.</p>
<p>Now we cluster. Graph-based clustering is stochastic, so we set a seed first — and, following the rule above, we cluster on the <strong>PCA</strong> coordinates, not on the UMAP.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1234</span><span class="op">)</span></span>
<span><span class="va">sce</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/scrapper/man/clusterGraph.se.html">clusterGraph.se</a></span><span class="op">(</span><span class="va">sce</span>, reddim.type<span class="op">=</span><span class="st">"PCA"</span><span class="op">)</span></span>
<span><span class="va">nn.clusters</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">sce</span><span class="op">$</span><span class="va">clusters</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">nn.clusters</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>nn.clusters
  1   2   3   4   5   6   7   8   9  10  11  12  13  14 
288 218 208 213 486 185 190  65  98 432 106 263  87 166 </code></pre>
</div>
</div>
<p>The <code><a href="https://rdrr.io/pkg/scrapper/man/clusterGraph.se.html">clusterGraph.se()</a></code> function uses graph-based clustering to identify groups of similar cells. Graph-based clustering was <a href="https://satijalab.org/seurat/articles/pbmc3k_tutorial.html#cluster-the-cells">popularized by the Seurat package</a>: it builds a nearest-neighbor graph and then finds communities within it, and the resulting clusters often correspond to distinct cell types or states. It writes the assignments to a <code>clusters</code> column in <code>colData(sce)</code>; we wrap them in a factor and keep a copy in <code>nn.clusters</code>. The <code>reddim.type="PCA"</code> argument points it at the denoised PCA space — the full set of principal components carries far more signal than the two UMAP axes, which exist only for viewing. Other methods exist (k-means, hierarchical clustering), but graph-based clustering suits single-cell data because it handles complex, non-linear structure and scales well.</p>
<p>The table above is your first concrete result: each entry is the number of cells assigned to a cluster, so you can read off how many groups the algorithm found and roughly how balanced they are. A handful of large clusters plus several small ones is typical — the large ones are usually abundant cell types, the small ones rare populations.</p>
</section><section id="visualizing-cell-types-and-clusters" class="level3 page-columns page-full" data-number="39.3.3"><h3 data-number="39.3.3" class="anchored" data-anchor-id="visualizing-cell-types-and-clusters">
<span class="header-section-number">39.3.3</span> Visualizing cell types and clusters</h3>
<p>This dataset ships with pre-defined cell type annotations in the <code>level1class</code> and <code>level2class</code> columns, which we can use to color the UMAP and see how well the structure lines up with known biology. The <code><a href="https://rdrr.io/pkg/scater/man/plotReducedDim.html">plotReducedDim()</a></code> function from the <code>scater</code> package draws a scatter plot of any stored embedding, coloring the points by cluster assignment or any cell metadata.</p>
<div class="cell page-columns page-full">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://bioconductor.org/packages/scater/">scater</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/SingleCellExperiment/man/colLabels.html">colLabels</a></span><span class="op">(</span><span class="va">sce</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="va">nn.clusters</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/scater/man/plotReducedDim.html">plotReducedDim</a></span><span class="op">(</span><span class="va">sce</span>, <span class="st">"UMAP"</span>, colour_by<span class="op">=</span><span class="st">"level1class"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display page-columns page-full">
<div id="fig-level1-class" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" width="672">
<figure class="quarto-float quarto-float-fig figure page-columns page-full"><div aria-describedby="fig-level1-class-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="setup_files/figure-html/fig-level1-class-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;39.3: "><img src="setup_files/figure-html/fig-level1-class-1.png" id="fig-level1-class" class="img-fluid figure-img" width="672"></a>
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig quarto-uncaptioned margin-caption" id="fig-level1-class-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;39.3
</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-level1-class" class="quarto-xref">Figure&nbsp;<span>39.3</span></a> is the payoff of the whole workflow so far. Each point is a cell, placed by UMAP so that similar cells sit close together, and colored by its known <code>level1class</code> cell type. Because cells of the same type fall into the same visual island, you can see at a glance that the unsupervised steps — normalization, HVG selection, PCA, UMAP — recovered real biology: the broad cell types separate cleanly without ever being told what they were.</p>
<p>We can also visualize the second, finer level of cell type annotations.</p>
<div class="cell page-columns page-full">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/scater/man/plotReducedDim.html">plotReducedDim</a></span><span class="op">(</span><span class="va">sce</span>, <span class="st">"UMAP"</span>, colour_by<span class="op">=</span><span class="st">"level2class"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display page-columns page-full">
<div id="fig-level2-class" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" width="672">
<figure class="quarto-float quarto-float-fig figure page-columns page-full"><div aria-describedby="fig-level2-class-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="setup_files/figure-html/fig-level2-class-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;39.4: "><img src="setup_files/figure-html/fig-level2-class-1.png" id="fig-level2-class" class="img-fluid figure-img" width="672"></a>
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig quarto-uncaptioned margin-caption" id="fig-level2-class-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;39.4
</figcaption></figure>
</div>
</div>
</div>
<p>And overlay additional metadata such as tissue type. The <code>shape_by</code> argument differentiates points by another categorical variable.</p>
<div class="cell page-columns page-full">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/scater/man/plotReducedDim.html">plotReducedDim</a></span><span class="op">(</span><span class="va">sce</span>, <span class="st">"UMAP"</span>, colour_by<span class="op">=</span><span class="st">"level1class"</span>, shape_by<span class="op">=</span><span class="st">"tissue"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display page-columns page-full">
<div id="fig-level1-tissue" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" width="672">
<figure class="quarto-float quarto-float-fig figure page-columns page-full"><div aria-describedby="fig-level1-tissue-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="setup_files/figure-html/fig-level1-tissue-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure&nbsp;39.5: "><img src="setup_files/figure-html/fig-level1-tissue-1.png" id="fig-level1-tissue" class="img-fluid figure-img" width="672"></a>
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig quarto-uncaptioned margin-caption" id="fig-level1-tissue-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;39.5
</figcaption></figure>
</div>
</div>
</div>
</section><section id="t-sne-vs-umap" class="level3 page-columns page-full" data-number="39.3.4"><h3 data-number="39.3.4" class="anchored" data-anchor-id="t-sne-vs-umap">
<span class="header-section-number">39.3.4</span> t-SNE vs UMAP</h3>
<p>UMAP didn’t appear from nowhere — for years <strong>t-SNE</strong> (t-distributed Stochastic Neighbor Embedding) was the default single-cell map, and you’ll still meet it everywhere. It’s worth running both once to see how they differ. Both start from the same PCA input; t-SNE optimizes for <em>local</em> neighbourhoods, which tends to spread clusters into well-separated blobs, while UMAP keeps more of the global layout and runs faster on large data.</p>
<div class="cell page-columns page-full">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://patchwork.data-imaginist.com">patchwork</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1234</span><span class="op">)</span></span>
<span><span class="va">sce</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/scrapper/man/runTsne.se.html">runTsne.se</a></span><span class="op">(</span><span class="va">sce</span>, reddim.type<span class="op">=</span><span class="st">"PCA"</span><span class="op">)</span></span>
<span><span class="va">p_umap</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/scater/man/plotReducedDim.html">plotReducedDim</a></span><span class="op">(</span><span class="va">sce</span>, <span class="st">"UMAP"</span>, colour_by<span class="op">=</span><span class="st">"level1class"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">"UMAP"</span><span class="op">)</span></span>
<span><span class="va">p_tsne</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/scater/man/plotReducedDim.html">plotReducedDim</a></span><span class="op">(</span><span class="va">sce</span>, <span class="st">"TSNE"</span>, colour_by<span class="op">=</span><span class="st">"level1class"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">"t-SNE"</span><span class="op">)</span></span>
<span><span class="op">(</span><span class="va">p_umap</span> <span class="op">|</span> <span class="va">p_tsne</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://patchwork.data-imaginist.com/reference/plot_layout.html">plot_layout</a></span><span class="op">(</span>guides <span class="op">=</span> <span class="st">"collect"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display page-columns page-full">
<div id="fig-tsne-umap" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full"><div aria-describedby="fig-tsne-umap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="setup_files/figure-html/fig-tsne-umap-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure&nbsp;39.6: The same cells, the same PCA input, two embeddings — colored by level1class. Both recover the same cell-type islands; the choice between them is about readability and speed, not correctness. In neither plot should the distances between islands be read quantitatively."><img src="setup_files/figure-html/fig-tsne-umap-1.png" class="img-fluid figure-img" width="960"></a>
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-tsne-umap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;39.6: The same cells, the same PCA input, two embeddings — colored by <code>level1class</code>. Both recover the same cell-type islands; the choice between them is about readability and speed, not correctness. In neither plot should the distances <em>between</em> islands be read quantitatively.
</figcaption></figure>
</div>
</div>
</div>
<p>The reassuring result is that both embeddings tell the same story — the same cell types form the same islands. They are two readable pictures of one underlying structure, and modern workflows reach for UMAP first. From here on we’ll stick with the UMAP.</p>
</section></section><section id="finding-marker-genes" class="level2 page-columns page-full" data-number="39.4"><h2 data-number="39.4" class="anchored" data-anchor-id="finding-marker-genes">
<span class="header-section-number">39.4</span> Finding marker genes</h2>
<p>Marker genes are genes that are differentially expressed in a specific cell type or cluster compared to others. Identifying marker genes helps us understand the molecular characteristics of each cell type and can provide insights into their functions.</p>
<p>To find marker genes, we use the <code><a href="https://rdrr.io/pkg/scrapper/man/scoreMarkers.html">scoreMarkers()</a></code> function from the <code>scrapper</code> package. For every group, it compares each gene’s expression against every <em>other</em> group and summarizes the result as an <strong>effect size</strong> — here we use Cohen’s <em>d</em>, a standardized difference in mean expression. A gene that is strongly and consistently higher in one group than in all the others gets a large effect size for that group, marking it as a good marker.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">markers</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/scrapper/man/scoreMarkers.html">scoreMarkers</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/SingleCellExperiment/man/assays.html">logcounts</a></span><span class="op">(</span><span class="va">sce</span><span class="op">)</span><span class="op">[</span><span class="va">top_var_genes</span>, <span class="op">]</span>,</span>
<span>                        groups<span class="op">=</span><span class="fu">colData</span><span class="op">(</span><span class="va">sce</span><span class="op">)</span><span class="op">$</span><span class="va">level1class</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We pass <code>logcounts(sce)[top_var_genes, ]</code> — the log-normalized matrix restricted to the highly variable genes we identified earlier, which are more likely to be informative for distinguishing cell types — and <code>groups=...</code> tells the function which cell type each cell belongs to.</p>
<p>The resulting <code>markers</code> object is a list. The piece we want is <code>markers$cohens.d</code>: a per-group list of tables, one row per gene, whose <code>mean</code> column is that gene’s average Cohen’s <em>d</em> across all pairwise comparisons. Ranking a group’s genes by that column, from largest to smallest, puts its best markers on top. The small helper below does exactly that, and we reuse it whenever we need ranked markers.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Rank a group's genes by mean Cohen's d (largest effect size first).</span></span>
<span><span class="va">rank_markers</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">effects</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">effects</span><span class="op">)</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/order.html">order</a></span><span class="op">(</span><span class="va">effects</span><span class="op">$</span><span class="va">mean</span>, decreasing<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span><span class="op">]</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>A compact way to see all the groups at once is a heatmap: take the top genes from every group, then plot their expression across all the cells. The code below pulls the top 10 marker genes for each cell type, collapses them into one unique set, and draws a single heatmap. This lets us see which genes are most strongly associated with each cell type and how they differ from one another.</p>
<div class="cell page-columns page-full">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Heatmap of the top marker genes across all cell types</span></span>
<span><span class="va">top_marker_genes_for_all_clusters</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="va">markers</span><span class="op">$</span><span class="va">cohens.d</span>, <span class="kw">function</span><span class="op">(</span><span class="va">eff</span><span class="op">)</span> <span class="op">{</span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fu">rank_markers</span><span class="op">(</span><span class="va">eff</span><span class="op">)</span>, <span class="fl">10</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="op">}</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/scater/man/plotHeatmap.html">plotHeatmap</a></span><span class="op">(</span><span class="va">sce</span>, features<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unlist.html">unlist</a></span><span class="op">(</span><span class="va">top_marker_genes_for_all_clusters</span><span class="op">)</span><span class="op">)</span>,</span>
<span>    cluster_rows<span class="op">=</span><span class="cn">TRUE</span>, cluster_cols<span class="op">=</span><span class="cn">TRUE</span>, show_colnames<span class="op">=</span><span class="cn">FALSE</span>,</span>
<span>    main<span class="op">=</span><span class="st">"Top marker genes for all clusters"</span>,</span>
<span>    color_columns_by<span class="op">=</span><span class="st">"level1class"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display page-columns page-full">
<div id="fig-marker-heatmap" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" width="672">
<figure class="quarto-float quarto-float-fig figure page-columns page-full"><div aria-describedby="fig-marker-heatmap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="setup_files/figure-html/fig-marker-heatmap-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figure&nbsp;39.7: "><img src="setup_files/figure-html/fig-marker-heatmap-1.png" id="fig-marker-heatmap" class="img-fluid figure-img" width="672"></a>
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig quarto-uncaptioned margin-caption" id="fig-marker-heatmap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;39.7
</figcaption></figure>
</div>
</div>
</div>
<p>In <a href="#fig-marker-heatmap" class="quarto-xref">Figure&nbsp;<span>39.7</span></a> the columns are cells (grouped and colored by cell type) and the rows are marker genes. The blocky structure is what you’re after: each set of marker genes lights up in one band of cells and stays dim elsewhere, which is exactly what makes them useful as markers — they cleanly distinguish one population from the rest.</p>
<section id="markers-for-the-clusters-you-discovered" class="level3 page-columns page-full" data-number="39.4.1"><h3 data-number="39.4.1" class="anchored" data-anchor-id="markers-for-the-clusters-you-discovered">
<span class="header-section-number">39.4.1</span> Markers for the clusters you discovered</h3>
<p>The markers above were found per <em>curated cell type</em> — a shortcut this teaching dataset allows because it ships with <code>level1class</code> labels. A real analysis has no such labels: you find markers for the <strong>clusters you actually discovered</strong>, then use those markers to give each cluster an identity. Let’s do it that way. We ask <code><a href="https://rdrr.io/pkg/scrapper/man/scoreMarkers.html">scoreMarkers()</a></code> to compare the graph-based clusters stored in <code>colLabels(sce)</code> (the <code><a href="https://rdrr.io/pkg/scrapper/man/clusterGraph.se.html">clusterGraph.se()</a></code> output from earlier), take each cluster’s single top gene, and paint that gene’s expression onto the UMAP.</p>
<div class="cell page-columns page-full">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Find markers for the data-driven clusters (colLabels holds the clusterGraph.se</span></span>
<span><span class="co"># assignments), not the curated cell-type labels.</span></span>
<span><span class="va">cluster_markers</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/scrapper/man/scoreMarkers.html">scoreMarkers</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/SingleCellExperiment/man/assays.html">logcounts</a></span><span class="op">(</span><span class="va">sce</span><span class="op">)</span><span class="op">[</span><span class="va">top_var_genes</span>, <span class="op">]</span>,</span>
<span>                                groups <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/SingleCellExperiment/man/colLabels.html">colLabels</a></span><span class="op">(</span><span class="va">sce</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># The single top marker gene for each cluster (highest mean Cohen's d).</span></span>
<span><span class="va">top_per_cluster</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">vapply</a></span><span class="op">(</span><span class="va">cluster_markers</span><span class="op">$</span><span class="va">cohens.d</span>,</span>
<span>                          <span class="kw">function</span><span class="op">(</span><span class="va">eff</span><span class="op">)</span> <span class="fu">rank_markers</span><span class="op">(</span><span class="va">eff</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, <span class="fu"><a href="https://rdrr.io/r/base/character.html">character</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Paint the four largest clusters, each colored by its top marker's expression.</span></span>
<span><span class="va">biggest</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sort.html">sort</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/SingleCellExperiment/man/colLabels.html">colLabels</a></span><span class="op">(</span><span class="va">sce</span><span class="op">)</span><span class="op">)</span>, decreasing <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">4</span><span class="op">]</span></span>
<span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://patchwork.data-imaginist.com">patchwork</a></span><span class="op">)</span></span>
<span><span class="va">panels</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="va">biggest</span>, <span class="kw">function</span><span class="op">(</span><span class="va">cl</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">gene</span> <span class="op">&lt;-</span> <span class="va">top_per_cluster</span><span class="op">[[</span><span class="va">cl</span><span class="op">]</span><span class="op">]</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/scater/man/plotReducedDim.html">plotReducedDim</a></span><span class="op">(</span><span class="va">sce</span>, <span class="st">"UMAP"</span>, colour_by <span class="op">=</span> <span class="va">gene</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sprintf.html">sprintf</a></span><span class="op">(</span><span class="st">"cluster %s — %s"</span>, <span class="va">cl</span>, <span class="va">gene</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="op">}</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://patchwork.data-imaginist.com/reference/wrap_plots.html">wrap_plots</a></span><span class="op">(</span><span class="va">panels</span>, ncol <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display page-columns page-full">
<div id="fig-umap-cluster-markers" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full"><div aria-describedby="fig-umap-cluster-markers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="setup_files/figure-html/fig-umap-cluster-markers-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="Figure&nbsp;39.8: The four largest graph-based clusters, each UMAP colored by that cluster’s own top marker gene — found by scoreMarkers() on colLabels(sce), the data-driven clusters, not the curated labels. Each marker is most strongly expressed in and around its own cluster; some tag a whole island, while others pick out a sub-population within one. Painting a cluster’s marker onto the map this way is the visual basis for turning an anonymous cluster number into a named cell type."><img src="setup_files/figure-html/fig-umap-cluster-markers-1.png" class="img-fluid figure-img" width="672"></a>
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-umap-cluster-markers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;39.8: The four largest graph-based clusters, each UMAP colored by that cluster’s own top marker gene — found by <code><a href="https://rdrr.io/pkg/scrapper/man/scoreMarkers.html">scoreMarkers()</a></code> on <code>colLabels(sce)</code>, the data-driven clusters, <em>not</em> the curated labels. Each marker is most strongly expressed in and around its own cluster; some tag a whole island, while others pick out a sub-population within one. Painting a cluster’s marker onto the map this way is the visual basis for turning an anonymous cluster number into a named cell type.
</figcaption></figure>
</div>
</div>
</div>
<p>Each panel lifts out one cluster’s top gene and shows where it is expressed. Some markers tag a whole island cleanly; others light up only part of the large neuronal island, where several graph-based clusters coexist — a reminder that clustering on the PCs resolves finer structure than the 2-D map alone reveals. Either way, the logic is the engine of annotation: an anonymous cluster number plus its localized marker equals a callable cell identity, and we reached it without ever touching the curated labels. (The next section revisits the idea with those labels as an answer key.)</p>
</section></section><section id="from-clusters-to-cell-types-annotation" class="level2 page-columns page-full" data-number="39.5"><h2 data-number="39.5" class="anchored" data-anchor-id="from-clusters-to-cell-types-annotation">
<span class="header-section-number">39.5</span> From clusters to cell types: annotation</h2>
<p>Clustering handed us groups, but a group labeled “cluster 3” tells a biologist nothing. <strong>Annotation</strong> is the step that attaches a <em>biological identity</em> to each cluster, and it comes in two broad flavors — the same two the <a href="../single_cell/concepts.html">concepts chapter</a> lays out:</p>
<ul>
<li>
<strong>Reference-based</strong> — score each cell against an annotated reference atlas and transfer the closest label (e.g.&nbsp;<code>SingleR</code>, Azimuth). Fast and reproducible when a good reference exists for your tissue; it’s the first thing to reach for in a real project, though we won’t run it here.</li>
<li>
<strong>Marker-based</strong> — match each cluster’s marker genes against known cell-type signatures. This is the route we can take <em>right now</em>, because we already have marker genes in hand from the previous section.</li>
</ul>
<p>This dataset is unusual in shipping curated <code>level1class</code> labels, so we can <em>check</em> our marker-based reasoning against a trusted answer. Treat that as training wheels — in your own data those labels are exactly what you are trying to produce.</p>
<section id="painting-marker-genes-onto-the-map" class="level3 page-columns page-full" data-number="39.5.1"><h3 data-number="39.5.1" class="anchored" data-anchor-id="painting-marker-genes-onto-the-map">
<span class="header-section-number">39.5.1</span> Painting marker genes onto the map</h3>
<p>The heatmap showed marker genes as a block matrix. A complementary view is to paint a single marker gene’s expression straight onto the UMAP we built earlier, so you can see <em>where</em> it is expressed. Color the map by individual marker genes — the single top-ranked marker for each of several cell types — and watch each gene light up its own territory.</p>
<div class="cell page-columns page-full">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># The per-cell-type marker lists we built earlier are already named by cell type,</span></span>
<span><span class="co"># because scoreMarkers() was grouped by level1class.</span></span>
<span><span class="va">celltype_names</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">top_marker_genes_for_all_clusters</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># The single top marker gene for four representative cell types.</span></span>
<span><span class="va">show_types</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">celltype_names</span>, <span class="fl">4</span><span class="op">)</span></span>
<span><span class="va">top_one</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">vapply</a></span><span class="op">(</span><span class="va">top_marker_genes_for_all_clusters</span><span class="op">[</span><span class="va">show_types</span><span class="op">]</span>,</span>
<span>                  <span class="kw">function</span><span class="op">(</span><span class="va">g</span><span class="op">)</span> <span class="va">g</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, <span class="fu"><a href="https://rdrr.io/r/base/character.html">character</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://patchwork.data-imaginist.com">patchwork</a></span><span class="op">)</span></span>
<span><span class="va">panels</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_along</a></span><span class="op">(</span><span class="va">top_one</span><span class="op">)</span>, <span class="kw">function</span><span class="op">(</span><span class="va">i</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/scater/man/plotReducedDim.html">plotReducedDim</a></span><span class="op">(</span><span class="va">sce</span>, <span class="st">"UMAP"</span>, colour_by <span class="op">=</span> <span class="va">top_one</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sprintf.html">sprintf</a></span><span class="op">(</span><span class="st">"%s\n(%s)"</span>, <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">top_one</span><span class="op">)</span><span class="op">[</span><span class="va">i</span><span class="op">]</span>, <span class="va">top_one</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="op">}</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://patchwork.data-imaginist.com/reference/wrap_plots.html">wrap_plots</a></span><span class="op">(</span><span class="va">panels</span>, ncol <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display page-columns page-full">
<div id="fig-umap-markers" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full"><div aria-describedby="fig-umap-markers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="setup_files/figure-html/fig-umap-markers-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9" title="Figure&nbsp;39.9: The UMAP colored by the top marker gene of four representative cell types. Each marker concentrates in the island its cell type occupies — the spatial counterpart of the block structure in the marker heatmap."><img src="setup_files/figure-html/fig-umap-markers-1.png" class="img-fluid figure-img" width="672"></a>
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-umap-markers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;39.9: The UMAP colored by the top marker gene of four representative cell types. Each marker concentrates in the island its cell type occupies — the spatial counterpart of the block structure in the marker heatmap.
</figcaption></figure>
</div>
</div>
</div>
<p>Each marker concentrates in exactly the island its cell type occupies — visual confirmation that these genes earn the name “marker.”</p>
</section><section id="marker-lists-are-gene-sets" class="level3 page-columns page-full" data-number="39.5.2"><h3 data-number="39.5.2" class="anchored" data-anchor-id="marker-lists-are-gene-sets">
<span class="header-section-number">39.5.2</span> Marker lists are gene sets</h3>
<p>Here is the idea worth carrying away. A cell type’s marker genes are nothing more — and nothing less — than a <strong>gene set</strong>: a named list of genes that, together, characterize a biological state. Deciding whether a cluster <em>is</em> a given cell type then becomes “is this gene set collectively high in these cells?” — which is exactly the question gene-set and pathway-enrichment analysis asks, only pointed at cell-type signatures instead of GO terms or KEGG pathways.</p>
<p>We can make that concrete with the simplest possible score — the mean log-expression of a marker set in each cell — and paint it onto the map:</p>
<div class="cell page-columns page-full">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># A cell type's marker genes ARE a gene set; score each cell by the set's mean.</span></span>
<span><span class="va">score_gene_set</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">sce</span>, <span class="va">genes</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">genes</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sets.html">intersect</a></span><span class="op">(</span><span class="va">genes</span>, <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">sce</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">colMeans</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/SingleCellExperiment/man/assays.html">logcounts</a></span><span class="op">(</span><span class="va">sce</span><span class="op">)</span><span class="op">[</span><span class="va">genes</span>, , drop <span class="op">=</span> <span class="cn">FALSE</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="va">target</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/grep.html">grep</a></span><span class="op">(</span><span class="st">"interneuron"</span>, <span class="va">celltype_names</span>, value <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">target</span><span class="op">)</span><span class="op">)</span> <span class="va">target</span> <span class="op">&lt;-</span> <span class="va">celltype_names</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>   <span class="co"># fall back if naming differs</span></span>
<span><span class="va">sce</span><span class="op">$</span><span class="va">marker_score</span> <span class="op">&lt;-</span> <span class="fu">score_gene_set</span><span class="op">(</span><span class="va">sce</span>, <span class="va">top_marker_genes_for_all_clusters</span><span class="op">[[</span><span class="va">target</span><span class="op">]</span><span class="op">]</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/scater/man/plotReducedDim.html">plotReducedDim</a></span><span class="op">(</span><span class="va">sce</span>, <span class="st">"UMAP"</span>, colour_by <span class="op">=</span> <span class="st">"marker_score"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sprintf.html">sprintf</a></span><span class="op">(</span><span class="st">"Module score for the %s marker set"</span>, <span class="va">target</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display page-columns page-full">
<div id="fig-umap-score" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full"><div aria-describedby="fig-umap-score-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="setup_files/figure-html/fig-umap-score-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10" title="Figure&nbsp;39.10: A ‘module score’ — the mean log-expression of a cell type’s marker set — painted onto the UMAP. Scoring cells against a set of genes (here the interneuron markers) is the same operation as gene-set / pathway scoring; the high-scoring cells localize to the interneuron island."><img src="setup_files/figure-html/fig-umap-score-1.png" class="img-fluid figure-img" width="672"></a>
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-umap-score-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;39.10: A ‘module score’ — the mean log-expression of a cell type’s marker set — painted onto the UMAP. Scoring cells against a <em>set</em> of genes (here the interneuron markers) is the same operation as gene-set / pathway scoring; the high-scoring cells localize to the interneuron island.
</figcaption></figure>
</div>
</div>
</div>
<p>The high-scoring cells pile onto a single island — the same one the curated labels call interneurons. A whole <em>set</em> of genes, scored together and pointed at a cell type, exactly as a pathway score points at a pathway.</p>
<p>Real annotation tools formalize this same move. Marker-set scorers like <code>AUCell</code> and <code>UCell</code> swap our crude mean for a rank-based enrichment statistic; reference-based methods like <code>SingleR</code> score each cell against <em>many</em> signatures at once and assign the best fit. The mental model is identical to gene-set analysis — only the gene sets have changed.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Mind the double dip
</div>
</div>
<div class="callout-body-container callout-body">
<p>We derived these marker sets <em>from these very clusters</em>, so scoring the same cells with them is somewhat circular — it confirms internal consistency, not external truth (the <a href="../single_cell/concepts.html">concepts chapter</a> unpacks this “double-dipping” trap). Honest annotation scores cells against marker sets defined <em>independently</em> — from a reference atlas or the literature — which is why reference-based methods are the gold standard when a reference exists.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Annotation ≈ gene-set analysis
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you remember one thing from this section: <strong>annotating cells by marker lists and testing gene sets for enrichment are the same operation.</strong> A cell-type signature is a gene set; a module score is an enrichment score; choosing the best-scoring label is choosing the most enriched set. Learn one and you have largely learned the other.</p>
</div>
</div>
</section></section><section id="interactive-visualization-with-isee" class="level2" data-number="39.6"><h2 data-number="39.6" class="anchored" data-anchor-id="interactive-visualization-with-isee">
<span class="header-section-number">39.6</span> Interactive visualization with iSEE</h2>
<p>The <a href="https://www.bioconductor.org/packages/release/bioc/html/iSEE.html">Interactive SummarizedExperiment Explorer (iSEE)</a> is a powerful tool for exploring single-cell data interactively. It allows us to visualize and interact with the data in real-time, making it easier to explore complex datasets and identify patterns.</p>
<p>A key component of iSEE is the <code>SingleCellExperiment</code> object, which serves as the data container for single-cell RNA-seq data. iSEE provides a user-friendly interface for exploring the data.</p>
<p>To use iSEE, we first need to install the <code>iSEE</code> package and then launch the iSEE app.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Install iSEE package if not already installed</span></span>
<span><span class="fu">iSEE</span><span class="fu">::</span><span class="fu">iSEE</span><span class="op">(</span><span class="va">sce</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The <code>iSEE()</code> function launches the iSEE app, which provides an interactive interface for exploring the <code>SingleCellExperiment</code> object.</p>
<p>You may want to play with a few genes to see how they are expressed across the different clusters. You can also explore the metadata associated with the cells, such as tissue type, cell type annotations, and quality control metrics. The set of “marker genes” we identified earlier can also be visualized in iSEE, allowing us to see how these genes are expressed across different clusters and cell types.</p>
<p>For the first cell type (astrocytes_ependymal), the marker genes are:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="va">top_marker_genes_for_all_clusters</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span>,<span class="st">'\n'</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Slc1a3 
 Clu 
 Gpr37l1 
 Apoe 
 Gja1 
 Mt2 
 Pla2g7 
 Aqp4 
 Mt1 
 Atp1a2 </code></pre>
</div>
</div>
<p>Try entering a couple of those gene names into the iSEE feature-expression panels to see how they vary across the clusters.</p>
</section><section id="exercises" class="level2 page-columns page-full" data-number="39.7"><h2 data-number="39.7" class="anchored" data-anchor-id="exercises">
<span class="header-section-number">39.7</span> Exercises</h2>
<p>These build directly on the <code>sce</code> object you created above. If you’ve closed your session, re-run the chapter up to the marker-gene step first.</p>
<ol type="1" class="page-columns page-full">
<li>
<p><strong>Read the cluster table.</strong> How many clusters did <code><a href="https://rdrr.io/pkg/scrapper/man/clusterGraph.se.html">clusterGraph.se()</a></code> find, and which is the largest? Which function’s output answers this?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">nn.clusters</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>nn.clusters
  1   2   3   4   5   6   7   8   9  10  11  12  13  14 
288 218 208 213 486 185 190  65  98 432 106 263  87 166 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">nn.clusters</span><span class="op">)</span><span class="op">)</span>   <span class="co"># number of clusters</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/which.min.html">which.max</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">nn.clusters</span><span class="op">)</span><span class="op">)</span> <span class="co"># the most populous cluster</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>5 
5 </code></pre>
</div>
</div>
<p><code><a href="https://rdrr.io/r/base/table.html">table()</a></code> counts cells per cluster; <code>length(unique(...))</code> turns that into the number of groups. The largest cluster is usually an abundant cell type rather than a rare one.</p>
</div>
</div>
</div>
</li>
<li>
<p><strong>Tune the number of variable genes.</strong> Re-select the top variable genes asking for only 500 instead of 2000. (<code><a href="https://rdrr.io/pkg/scrapper/man/chooseRnaHvgs.se.html">chooseRnaHvgs.se()</a></code> already stored each gene’s variability as the <code>residuals</code> column of <code>rowData(sce)</code>, so you can re-rank without re-modelling.) Does the size of the gene set change which features you’d carry into PCA?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">top_500_idx</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/scrapper/man/chooseHighlyVariableGenes.html">chooseHighlyVariableGenes</a></span><span class="op">(</span><span class="fu">rowData</span><span class="op">(</span><span class="va">sce</span><span class="op">)</span><span class="op">$</span><span class="va">residuals</span>, top<span class="op">=</span><span class="fl">500</span><span class="op">)</span></span>
<span><span class="va">top_500</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">sce</span><span class="op">)</span><span class="op">[</span><span class="va">top_500_idx</span><span class="op">]</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">top_500</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 500</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sets.html">intersect</a></span><span class="op">(</span><span class="va">top_500</span>, <span class="va">top_var_genes</span><span class="op">)</span><span class="op">)</span>  <span class="co"># overlap with the 2000-gene set</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 500</code></pre>
</div>
</div>
<p>The 500 genes are (almost entirely) a subset of the 2000 — they are simply the <em>most</em> variable ones. Picking fewer genes is faster and noisier; picking more keeps weaker signal at the cost of more noise. There is no single right answer, which is why it’s a choice you make deliberately.</p>
</div>
</div>
</div>
</li>
<li class="page-columns page-full">
<p><strong>Switch the coloring.</strong> Redraw the UMAP, but color the cells by their cluster label (<code>colour_by="label"</code>) instead of by the known cell type. How well do the data-driven clusters line up with the annotated cell types in <a href="#fig-level1-class" class="quarto-xref">Figure&nbsp;<span>39.3</span></a>?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/scater/man/plotReducedDim.html">plotReducedDim</a></span><span class="op">(</span><span class="va">sce</span>, <span class="st">"UMAP"</span>, colour_by<span class="op">=</span><span class="st">"label"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-umap-by-cluster" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure" aria-labelledby="fig-umap-by-cluster-caption"><div aria-describedby="fig-umap-by-cluster-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="setup_files/figure-html/fig-umap-by-cluster-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11" title="Figure&nbsp;39.11: "><img src="setup_files/figure-html/fig-umap-by-cluster-1.png" id="fig-umap-by-cluster" class="img-fluid figure-img" width="672"></a>
</div>
</figure>
</div>
</div>
</div>
<p>Each cluster occupies its own island, and those islands correspond closely to the cell-type islands you saw earlier — evidence that the unsupervised clustering recovered the same structure as the curated annotations.</p>
</div>
</div>
</div>
<div id="fig-umap-by-cluster-caption" class="margin-figure-caption column-margin callout-8-contents callout-collapse collapse callout-margin-content">
Figure&nbsp;39.11
</div></li>
<li class="page-columns page-full">
<p><strong>Score a different cell type.</strong> Pick another entry of <code>celltype_names</code> — say an oligodendrocyte or astrocyte type — recompute the module score for <em>its</em> marker set, and redraw the UMAP. Does the high-scoring region land on that cell type’s island in <a href="#fig-level1-class" class="quarto-xref">Figure&nbsp;<span>39.3</span></a>?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">target2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/grep.html">grep</a></span><span class="op">(</span><span class="st">"oligodendrocyte"</span>, <span class="va">celltype_names</span>, value <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">target2</span><span class="op">)</span><span class="op">)</span> <span class="va">target2</span> <span class="op">&lt;-</span> <span class="va">celltype_names</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>   <span class="co"># fall back if naming differs</span></span>
<span><span class="va">sce</span><span class="op">$</span><span class="va">marker_score2</span> <span class="op">&lt;-</span> <span class="fu">score_gene_set</span><span class="op">(</span><span class="va">sce</span>, <span class="va">top_marker_genes_for_all_clusters</span><span class="op">[[</span><span class="va">target2</span><span class="op">]</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/scater/man/plotReducedDim.html">plotReducedDim</a></span><span class="op">(</span><span class="va">sce</span>, <span class="st">"UMAP"</span>, colour_by <span class="op">=</span> <span class="st">"marker_score2"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sprintf.html">sprintf</a></span><span class="op">(</span><span class="st">"Module score for the %s marker set"</span>, <span class="va">target2</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-umap-score-oligo" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure" aria-labelledby="fig-umap-score-oligo-caption"><div aria-describedby="fig-umap-score-oligo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="setup_files/figure-html/fig-umap-score-oligo-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12" title="Figure&nbsp;39.12: "><img src="setup_files/figure-html/fig-umap-score-oligo-1.png" id="fig-umap-score-oligo" class="img-fluid figure-img" width="672"></a>
</div>
</figure>
</div>
</div>
</div>
<p>The hot spot moves to a different island — the one the curated labels call oligodendrocytes. Same machinery, different gene set: that is the whole point of treating annotation as gene-set scoring.</p>
</div>
</div>
</div>
<div id="fig-umap-score-oligo-caption" class="margin-figure-caption column-margin callout-9-contents callout-collapse collapse callout-margin-content">
Figure&nbsp;39.12
</div></li>
</ol></section><section id="summary" class="level2" data-number="39.8"><h2 data-number="39.8" class="anchored" data-anchor-id="summary">
<span class="header-section-number">39.8</span> Summary</h2>
<p>You took a published mouse-brain dataset all the way from raw counts to a labeled map of cell types, and in doing so walked the standard scRNA-seq workflow:</p>
<ul>
<li>
<strong>Loaded</strong> the data as a <code>SingleCellExperiment</code> — a <code>SummarizedExperiment</code> (the <a href="../bioc-summarizedexperiment.html">SummarizedExperiment chapter</a>) with single-cell extras like a reduced-dimensions slot.</li>
<li>
<strong>Log-normalized</strong> the counts with <code><a href="https://rdrr.io/pkg/scrapper/man/normalizeRnaCounts.se.html">normalizeRnaCounts.se()</a></code> to correct for differences in sequencing depth between cells.</li>
<li>
<strong>Selected highly variable genes</strong> with <code><a href="https://rdrr.io/pkg/scrapper/man/chooseRnaHvgs.se.html">chooseRnaHvgs.se()</a></code>, focusing the analysis on the genes that carry biological signal.</li>
<li>
<strong>Reduced dimensions</strong> with <code><a href="https://rdrr.io/pkg/scrapper/man/runPca.se.html">runPca.se()</a></code> and then <code><a href="https://rdrr.io/pkg/scrapper/man/runUmap.se.html">runUmap.se()</a></code> (with a t-SNE comparison), collapsing thousands of genes into a 2D map.</li>
<li>
<strong>Clustered</strong> the cells with <code><a href="https://rdrr.io/pkg/scrapper/man/clusterGraph.se.html">clusterGraph.se()</a></code> on the PCA coordinates — not the 2-D embedding — and read the cluster table to see how many groups emerged.</li>
<li>
<strong>Found and visualized marker genes</strong> with <code><a href="https://rdrr.io/pkg/scrapper/man/scoreMarkers.html">scoreMarkers()</a></code> and <code><a href="https://rdrr.io/pkg/scater/man/plotHeatmap.html">plotHeatmap()</a></code>, confirming that each cluster has its own molecular fingerprint.</li>
<li>
<strong>Connected markers to identity</strong> by painting them onto a UMAP and scoring marker <em>sets</em> as a module score — framing cell-type annotation as the same operation as gene-set enrichment.</li>
</ul>
<p>The reassuring result was that the unsupervised steps recovered the known cell types: clusters and curated labels landed on the same islands of the t-SNE and UMAP. From here you could reach for a reference-based annotator like <code>SingleR</code>, compare conditions across samples (the <a href="../single_cell/concepts.html">concepts chapter</a>’s Part B), or hand the object to an interactive explorer like iSEE.</p>
</section><section id="bonus-working-with-10x-genomics-data" class="level2" data-number="39.9"><h2 data-number="39.9" class="anchored" data-anchor-id="bonus-working-with-10x-genomics-data">
<span class="header-section-number">39.9</span> Bonus: working with 10x Genomics data</h2>
<p>The rest of the chapter is an optional appendix. Everything above used a curated dataset that arrives already cleaned and annotated. Real projects rarely start there: most droplet-based experiments come off a 10x Genomics platform as raw output that you must load and quality-control yourself. The code in this section is not executed (the files don’t exist in this book), but it shows the shape of that early workflow so you’ll recognize it when you meet it.</p>
<section id="understanding-10x-genomics-output-formats" class="level3" data-number="39.9.1"><h3 data-number="39.9.1" class="anchored" data-anchor-id="understanding-10x-genomics-output-formats">
<span class="header-section-number">39.9.1</span> Understanding 10x Genomics output formats</h3>
<p>10x Genomics Cell Ranger produces several output formats:</p>
<ol type="1">
<li>
<strong>Matrix Market format</strong> (<code>.mtx</code> files): Sparse matrix format with separate files for the matrix, gene names, and cell barcodes</li>
<li>
<strong>HDF5 format</strong> (<code>.h5</code> files): A single compressed file containing all the data</li>
<li>
<strong>Filtered vs.&nbsp;unfiltered</strong>: Cell Ranger provides both versions - filtered contains only cells that pass basic quality filters</li>
</ol></section><section id="loading-10x-data-from-matrix-market-files" class="level3" data-number="39.9.2"><h3 data-number="39.9.2" class="anchored" data-anchor-id="loading-10x-data-from-matrix-market-files">
<span class="header-section-number">39.9.2</span> Loading 10x data from Matrix Market files</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Loading from standard 10x output directory</span></span>
<span><span class="co"># This assumes you have a directory with:</span></span>
<span><span class="co"># - matrix.mtx.gz (or matrix.mtx)</span></span>
<span><span class="co"># - features.tsv.gz (or genes.tsv.gz for older versions)</span></span>
<span><span class="co"># - barcodes.tsv.gz</span></span>
<span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">DropletUtils</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">SingleCellExperiment</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Method 1: Using DropletUtils (recommended)</span></span>
<span><span class="va">sce_10x</span> <span class="op">&lt;-</span> <span class="fu">read10xCounts</span><span class="op">(</span><span class="st">"path/to/10x/output/"</span>, col.names <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Method 2: Using Seurat (if you prefer the Seurat ecosystem)</span></span>
<span><span class="co"># library(Seurat)</span></span>
<span><span class="co"># seurat_obj &lt;- Read10X("path/to/10x/output/")</span></span>
<span><span class="co"># sce_10x &lt;- as.SingleCellExperiment(CreateSeuratObject(seurat_obj))</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>What we’re doing:</strong> The <code>read10xCounts()</code> function from DropletUtils reads the three files that comprise 10x output and creates a SingleCellExperiment object. The <code>col.names = TRUE</code> parameter ensures that cell barcodes are used as column names.</p>
<p><strong>Why DropletUtils:</strong> This package is specifically designed for handling droplet-based single-cell data (like 10x Genomics). It includes specialized functions for:</p>
<ul>
<li>Reading 10x formats efficiently</li>
<li>Distinguishing empty droplets from cells</li>
<li>Handling ambient RNA contamination</li>
<li>Quality control specific to droplet-based methods</li>
</ul></section><section id="loading-from-hdf5-files" class="level3" data-number="39.9.3"><h3 data-number="39.9.3" class="anchored" data-anchor-id="loading-from-hdf5-files">
<span class="header-section-number">39.9.3</span> Loading from HDF5 files</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb41"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># For HDF5 format files</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://huber-group-embl.github.io/rhdf5/">rhdf5</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Method 1: Using DropletUtils</span></span>
<span><span class="va">sce_h5</span> <span class="op">&lt;-</span> <span class="fu">read10xCounts</span><span class="op">(</span><span class="st">"path/to/sample.h5"</span>, type <span class="op">=</span> <span class="st">"HDF5"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Method 2: Direct HDF5 reading (more control)</span></span>
<span><span class="va">h5_file</span> <span class="op">&lt;-</span> <span class="st">"path/to/sample.h5"</span></span>
<span><span class="va">gene_info</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://huber-group-embl.github.io/rhdf5/reference/h5_read.html">h5read</a></span><span class="op">(</span><span class="va">h5_file</span>, <span class="st">"matrix/features"</span><span class="op">)</span></span>
<span><span class="va">barcodes</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://huber-group-embl.github.io/rhdf5/reference/h5_read.html">h5read</a></span><span class="op">(</span><span class="va">h5_file</span>, <span class="st">"matrix/barcodes"</span><span class="op">)</span></span>
<span><span class="va">matrix_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://huber-group-embl.github.io/rhdf5/reference/h5_read.html">h5read</a></span><span class="op">(</span><span class="va">h5_file</span>, <span class="st">"matrix/data"</span><span class="op">)</span></span>
<span><span class="co"># Additional processing needed to reconstruct sparse matrix</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>What we’re doing:</strong> HDF5 files are more convenient as they contain all information in a single file. The <code>type = "HDF5"</code> parameter tells the function to expect this format instead of separate matrix files.</p>
<p><strong>When to use H5 files:</strong></p>
<ul>
<li>
<strong>Convenience</strong>: Single file is easier to manage and transfer</li>
<li>
<strong>Speed</strong>: Often faster to read than multiple compressed files</li>
<li>
<strong>Storage</strong>: More efficient storage, especially for large datasets</li>
</ul></section><section id="essential-quality-control-after-loading-raw-data" class="level3" data-number="39.9.4"><h3 data-number="39.9.4" class="anchored" data-anchor-id="essential-quality-control-after-loading-raw-data">
<span class="header-section-number">39.9.4</span> Essential quality control after loading raw data</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Add mitochondrial gene information</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">scuttle</span><span class="op">)</span></span>
<span><span class="va">is.mito</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/grep.html">grepl</a></span><span class="op">(</span><span class="st">"^MT-"</span>, <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">sce_10x</span><span class="op">)</span><span class="op">)</span> <span class="co"># Human mitochondrial genes</span></span>
<span><span class="co"># For mouse data, use: is.mito &lt;- grepl("^mt-", rownames(sce_10x))</span></span>
<span></span>
<span><span class="co"># Calculate per-cell QC metrics</span></span>
<span><span class="va">sce_10x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/scuttle/man/addPerCellQCMetrics.html">addPerCellQC</a></span><span class="op">(</span><span class="va">sce_10x</span>, subsets <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>Mito <span class="op">=</span> <span class="va">is.mito</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Calculate per-gene QC metrics</span></span>
<span><span class="va">sce_10x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/scuttle/man/addPerCellQCMetrics.html">addPerFeatureQC</a></span><span class="op">(</span><span class="va">sce_10x</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># View the QC metrics</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/SummarizedExperiment/man/SummarizedExperiment-class.html">colData</a></span><span class="op">(</span><span class="va">sce_10x</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>What we’re doing:</strong> We’re calculating quality control metrics that are essential for raw 10x data:</p>
<ul>
<li>
<strong>Mitochondrial genes</strong>: High mitochondrial gene expression often indicates dying cells</li>
<li>
<strong>Per-cell metrics</strong>: Total counts, number of detected genes, mitochondrial percentage</li>
<li>
<strong>Per-gene metrics</strong>: How many cells express each gene</li>
</ul>
<p><strong>Why QC is crucial for raw data:</strong> Unlike curated datasets, raw 10x data contains:</p>
<ul>
<li>
<strong>Empty droplets</strong>: Droplets that captured ambient RNA but no cells</li>
<li>
<strong>Dying cells</strong>: Cells with compromised membranes</li>
<li>
<strong>Doublets</strong>: Droplets containing multiple cells</li>
<li>
<strong>Low-quality cells</strong>: Cells with very few detected genes</li>
</ul></section><section id="filtering-low-quality-cells-and-genes" class="level3" data-number="39.9.5"><h3 data-number="39.9.5" class="anchored" data-anchor-id="filtering-low-quality-cells-and-genes">
<span class="header-section-number">39.9.5</span> Filtering low-quality cells and genes</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb43"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Visualize QC metrics</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://bioconductor.org/packages/scater/">scater</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/scater/man/plotColData.html">plotColData</a></span><span class="op">(</span><span class="va">sce_10x</span>, x <span class="op">=</span> <span class="st">"sum"</span>, y <span class="op">=</span> <span class="st">"detected"</span>, colour_by <span class="op">=</span> <span class="st">"subsets_Mito_percent"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Set filtering thresholds (these are examples - adjust based on your data)</span></span>
<span><span class="co"># Filter cells</span></span>
<span><span class="va">high_mito</span> <span class="op">&lt;-</span> <span class="va">sce_10x</span><span class="op">$</span><span class="va">subsets_Mito_percent</span> <span class="op">&gt;</span> <span class="fl">20</span>  <span class="co"># Remove cells with &gt;20% mitochondrial reads</span></span>
<span><span class="va">low_lib_size</span> <span class="op">&lt;-</span> <span class="va">sce_10x</span><span class="op">$</span><span class="va">sum</span> <span class="op">&lt;</span> <span class="fl">1000</span>              <span class="co"># Remove cells with &lt;1000 total counts</span></span>
<span><span class="va">low_n_features</span> <span class="op">&lt;-</span> <span class="va">sce_10x</span><span class="op">$</span><span class="va">detected</span> <span class="op">&lt;</span> <span class="fl">500</span>        <span class="co"># Remove cells with &lt;500 detected genes</span></span>
<span></span>
<span><span class="co"># Filter genes (remove genes expressed in very few cells)</span></span>
<span><span class="va">low_expression</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">rowSums</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/dge.html">counts</a></span><span class="op">(</span><span class="va">sce_10x</span><span class="op">)</span> <span class="op">&gt;</span> <span class="fl">0</span><span class="op">)</span> <span class="op">&lt;</span> <span class="fl">10</span>  <span class="co"># Expressed in &lt;10 cells</span></span>
<span></span>
<span><span class="co"># Apply filters</span></span>
<span><span class="va">sce_filtered</span> <span class="op">&lt;-</span> <span class="va">sce_10x</span><span class="op">[</span><span class="op">!</span><span class="va">low_expression</span>, <span class="op">!</span><span class="op">(</span><span class="va">high_mito</span> <span class="op">|</span> <span class="va">low_lib_size</span> <span class="op">|</span> <span class="va">low_n_features</span><span class="op">)</span><span class="op">]</span></span>
<span></span>
<span><span class="co"># Check how many cells and genes remain</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">sce_10x</span><span class="op">)</span>      <span class="co"># Before filtering</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">sce_filtered</span><span class="op">)</span> <span class="co"># After filtering</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>What we’re doing:</strong> We’re applying filters to remove low-quality cells and rarely expressed genes. The specific thresholds should be adjusted based on your dataset characteristics.</p>
<p><strong>Understanding the filters:</strong></p>
<ul>
<li>
<strong>Mitochondrial percentage</strong>: Cells with high mitochondrial gene expression are likely dying</li>
<li>
<strong>Library size</strong>: Total number of UMIs per cell - very low values suggest poor capture</li>
<li>
<strong>Number of features</strong>: How many different genes are detected - very low values suggest poor quality</li>
<li>
<strong>Gene expression frequency</strong>: Genes expressed in very few cells are often noise</li>
</ul>
<p><strong>Critical considerations:</strong></p>
<ul>
<li>
<strong>Thresholds are dataset-dependent</strong>: What works for one experiment may not work for another</li>
<li>
<strong>Biological vs.&nbsp;technical variation</strong>: Some cell types naturally have different RNA content</li>
<li>
<strong>Visualization first</strong>: Always plot your QC metrics before setting thresholds</li>
</ul></section></section><section id="further-reading-and-resources" class="level2" data-number="39.10"><h2 data-number="39.10" class="anchored" data-anchor-id="further-reading-and-resources">
<span class="header-section-number">39.10</span> Further reading and resources</h2>
<p>For more in-depth information on single-cell RNA-seq analysis, consider the following resources:</p>
<ul>
<li>The <a href="https://osca.bioconductor.org/">Orchestrating Single-Cell RNA-seq Analysis</a> book provides a comprehensive guide to single-cell RNA-seq analysis using Bioconductor.</li>
<li>The <a href="https://satijalab.org/seurat/">Seurat</a> package documentation offers extensive tutorials and vignettes for single-cell analysis in the Seurat ecosystem.</li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-doi:10.1038/s41592-019-0654-x" class="csl-entry" role="listitem">
Amezquita, Robert A., Aaron T. L. Lun, Etienne Becht, et al. 2019. <span>“Orchestrating Single-Cell Analysis with <span>Bioconductor</span>.”</span> <em>Nature Methods</em> 17 (2): 137–45. <a href="https://doi.org/10.1038/s41592-019-0654-x">https://doi.org/10.1038/s41592-019-0654-x</a>.
</div>
<div id="ref-doi:10.1371/journal.pcbi.1011288" class="csl-entry" role="listitem">
Chari, Tara, and Lior Pachter. 2023. <span>“The Specious Art of Single-Cell Genomics.”</span> <em>PLOS Computational Biology</em> 19 (8): e1011288. <a href="https://doi.org/10.1371/journal.pcbi.1011288">https://doi.org/10.1371/journal.pcbi.1011288</a>.
</div>
<div id="ref-lun2016" class="csl-entry" role="listitem">
Lun, Aaron T. L., Davis J. McCarthy, and John C. Marioni. 2016. <span>“A Step-by-Step Workflow for Low-Level Analysis of Single-Cell RNA-Seq Data with Bioconductor.”</span> <em>F1000Res.</em> 5: 2122. <a href="https://doi.org/10.12688/f1000research.9501.2">https://doi.org/10.12688/f1000research.9501.2</a>.
</div>
<div id="ref-McCarthy2017scater" class="csl-entry" role="listitem">
McCarthy, Davis J., Kieran R. Campbell, Aaron T. L. Lun, and Quin F. Willis. 2017. <span>“Scater: Pre-Processing, Quality Control, Normalisation and Visualisation of Single-Cell <span>R</span><span>N</span><span>A</span>-Seq Data in <span>R</span>.”</span> <em>Bioinformatics</em> 33: 1179–86. <a href="https://doi.org/10.1093/bioinformatics/btw777">https://doi.org/10.1093/bioinformatics/btw777</a>.
</div>
<div id="ref-risso2024scRNAseq" class="csl-entry" role="listitem">
Risso, Davide, and Michael Cole. 2024. <em>scRNAseq: Collection of Public Single-Cell RNA-Seq Datasets</em>. <a href="https://doi.org/10.18129/B9.bioc.scRNAseq">https://doi.org/10.18129/B9.bioc.scRNAseq</a>.
</div>
<div id="ref-zeiselCellTypesMouse2015" class="csl-entry" role="listitem">
Zeisel, Amit, Ana B. Muñoz-Manchado, Simone Codeluppi, et al. 2015. <span>“Cell Types in the Mouse Cortex and Hippocampus Revealed by Single-Cell <span class="nocase">RNA-seq</span>.”</span> <em>Science</em> 347 (6226): 1138–42. <a href="https://doi.org/10.1126/science.aaa1934">https://doi.org/10.1126/science.aaa1934</a>.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../single_cell/concepts.html" class="pagination-link" aria-label="How single-cell analysis works">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">How single-cell analysis works</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../single_cell/multiome.html" class="pagination-link" aria-label="Integrating single-cell ATAC and RNA">
        <span class="nav-page-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Integrating single-cell ATAC and RNA</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
<li class="nav-item">
    <a class="nav-link" href="../about.html">
<p>About</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="../contributors.html">
<p>Contributors</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="../license.html">
<p>License</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://doi.org/10.5281/zenodo.20574829">
<p>DOI: 10.5281/zenodo.20574829</p>
</a>
  </li>  
</ul>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/seandavi/RBiocBook/edit/main/single_cell/setup.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/seandavi/RBiocBook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li><li><a href="https://github.com/seandavi/RBiocBook/blob/main/single_cell/setup.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>


<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>