{
  "hash": "42bfb246f44f5524ceea08b0d5234d54",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Accessing public omics data with GEOquery\"\n---\n\nSomeone has already run the experiment you need. Thousands of expression\nstudies — microarray and RNA-seq, across nearly every tissue and disease — sit\nin a public archive called the **Gene Expression Omnibus (GEO)**, free to\ndownload and reanalyze. Suppose you read a paper comparing tumor and normal\ntissue across several cancers and you want to *see the data for yourself*:\npull it down, check how the samples group, and ask whether tumor and normal\nreally separate. That is exactly the kind of reuse GEO exists for.\n\nIn this chapter you'll do that end to end. You'll fetch a real published\ndataset with the `GEOquery` package, load it into a `SummarizedExperiment` (the\ncontainer from the previous chapter), keep the most variable genes, and run a\n**principal component analysis (PCA)** to visualize how the samples relate. The\ndata come from a study of immune gene expression in matched normal and tumor\ntissue [@brouwer-visser_regulatory_2018], deposited as accession\n[GSE103512][GSE103512].\n\n## What you'll learn\n\nBy the end of this chapter you will be able to:\n\n- Download a published dataset from GEO with `getGEO()`.\n- Convert the result into a `SummarizedExperiment` and inspect its parts.\n- Summarize sample annotations with `table()`.\n- Filter an expression matrix down to its most variable genes.\n- Run PCA with `prcomp()` and plot the samples to see how they group.\n\nThis chapter builds directly on the `SummarizedExperiment` chapter. If the words\n`assay()`, `colData()`, or \"rows are genes, columns are samples\" don't feel\nfamiliar yet, read that chapter first — here we'll lean on it rather than\nre-explain the object's anatomy.\n\n::: {.callout-tip}\n## Installing GEOquery\n\n`GEOquery` is a Bioconductor package. Install it once with `BiocManager`; you\nwon't need to run this again:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBiocManager::install(\"GEOquery\")\n```\n:::\n\n:::\n\n## Fetching a dataset from GEO\n\n`GEOquery` has essentially one function you'll reach for: `getGEO()`. You hand it\na GEO **accession number** — the unique ID for a dataset, here `\"GSE103512\"` —\nand it downloads the data over the network.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(GEOquery)\ngse <- getGEO(\"GSE103512\")[[1]]\n```\n:::\n\n\n::: {.callout-note}\n## Why the `[[1]]` and the conversion later?\n\nTwo small historical quirks are worth a moment, because they trip up everyone\nthe first time.\n\nFirst, `getGEO()` returns a **list** of datasets, not a single one. In the early\ndays a single accession could bundle several datasets, so the function always\nreturns a list. That's uncommon now, but the convention stayed because so much\nolder data is still useful — hence the `[[1]]` to grab the first (and here,\nonly) element.\n\nSecond, `GEOquery` was written in 2007 and hands you data in the older\nBioconductor container, the `ExpressionSet`. We'll convert it to the modern\n`SummarizedExperiment` in the next step so we can use the accessors you already\nknow.\n:::\n\nNow convert the `ExpressionSet` into a `SummarizedExperiment` with `as()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(SummarizedExperiment)\nse <- as(gse, \"SummarizedExperiment\")\nse\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass: SummarizedExperiment \ndim: 54715 280 \nmetadata(3): experimentData annotation protocolData\nassays(1): exprs\nrownames(54715): 1007_PM_s_at 1053_PM_at ... AFFX-TrpnX-5_at\n  AFFX-TrpnX-M_at\nrowData names(16): ID GB_ACC ... Gene.Ontology.Cellular.Component\n  Gene.Ontology.Molecular.Function\ncolnames(280): GSM2772660 GSM2772661 ... GSM2772938 GSM2772939\ncolData names(72): title geo_accession ... tumorsize.ch1 weight.ch1\n```\n\n\n:::\n:::\n\n\nPrinting `se` confirms what you have: a `SummarizedExperiment` whose rows are\ngenes (features) and whose columns are samples. The `assay()` holds the\nexpression matrix, and `colData()` holds the per-sample annotations — the same\nthree-part structure from the previous chapter.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(se)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 54715   280\n```\n\n\n:::\n:::\n\n\nSo this experiment has 54715 genes measured across 280 samples.\nThe expression values live in the assay named `\"exprs\"` (a leftover name from the\n`ExpressionSet` days), and you reach them with `assay(se, \"exprs\")`.\n\n## Summarizing the sample annotations\n\nBefore any analysis, look at what the samples *are*. The interesting variables\nhere are the cancer type and whether each sample is tumor or normal tissue.\nThey live in `colData(se)` under the names `cancer.type.ch1` and `normal.ch1`.\n\nThe `table()` function counts unique values, and `with()` lets you refer to\nthose column names directly instead of typing `colData(se)$...` for each one:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwith(colData(se), table(`cancer.type.ch1`, `normal.ch1`))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               normal.ch1\ncancer.type.ch1 no yes\n          BC    65  10\n          CRC   57  12\n          NSCLC 60   9\n          PCA   60   7\n```\n\n\n:::\n:::\n\n\nRead this as a grid: each row is a cancer type, and the two columns split it\ninto tumor (`no`, i.e. *not* normal) and normal samples. Most cancer types here\nhave both tumor and matched normal tissue, with tumor samples outnumbering\nnormals — exactly the design you'd want for a tumor-vs-normal comparison. A\nquick table like this is the cheapest possible sanity check that the dataset\ncontains what the paper claimed.\n\n## Keeping the most variable genes\n\nWe want to see how the samples group. Most of the genes barely change from\nsample to sample, and those flat genes only add noise. A standard move before\ndimensionality reduction is to keep just the **most variable** genes — the ones\nactually carrying the signal that distinguishes samples.\n\n::: {.callout-note}\n## Why filter to high-variance genes before PCA?\n\nPCA looks for the directions in which your samples differ most. A gene whose\nexpression is nearly constant everywhere contributes almost nothing to those\ndifferences — it's dead weight that dilutes the signal and slows the\ncomputation. Ranking genes by their **standard deviation** and keeping the top\nslice focuses PCA on the genes that vary, which usually makes the biological\nstructure (tumor vs. normal, one cancer type vs. another) far easier to see.\nThere's no single correct cutoff; 500 genes is a reasonable starting point, and\nyou're encouraged to try others.\n:::\n\nCompute each gene's standard deviation with `apply()` (which applies a function\nacross the rows or columns of a matrix — here, `sd` to each row, `1` meaning\n\"by row\"), then use `order()` to rank genes from most to least variable and keep\nthe top 500:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsds <- apply(assay(se, \"exprs\"), 1, sd)\ndat <- assay(se, \"exprs\")[order(sds, decreasing = TRUE)[1:500], ]\n```\n:::\n\n\n`order(sds, decreasing = TRUE)` returns the row positions sorted by standard\ndeviation, largest first; `[1:500]` takes the top 500; and we use those to\nsubset the expression matrix. `dat` is now a 500-gene by 280-sample\nmatrix.\n\n## Running and interpreting the PCA\n\nPCA finds new axes (principal components) that capture the largest patterns of\nvariation in the data. `prcomp()` expects **samples as rows**, so we transpose\nthe matrix with `t()` before handing it over:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npca_results <- prcomp(t(dat))\npca_df <- as.data.frame(pca_results$x)\npca_df$Type <- factor(colData(se)[, \"cancer.type.ch1\"])\npca_df$Normal <- factor(colData(se)[, \"normal.ch1\"])\n```\n:::\n\n\n`pca_results$x` holds each sample's coordinates along every principal component.\nWe pull those into a data frame and attach the cancer type and tumor/normal\nlabel so we can color and shape the plot.\n\nHow much of the variation does each component capture? Each component's variance\nis its squared standard deviation; divide by the total to get a fraction:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npca_var <- pca_results$sdev^2 / sum(pca_results$sdev^2)\nplot(pca_var, xlab = \"Principal component\", ylab = \"Variance explained\",\n     main = \"Variance explained by each principal component\", type = \"b\")\n```\n\n::: {.cell-output-display}\n![](geoquery_files/figure-html/pca-variance-1.png){width=672}\n:::\n:::\n\n\nThe curve drops off steeply: the first principal component (PC1) explains far\nmore of the variation than any other, and after the first few components each\none adds little. That steep drop is good news — it means a two-dimensional plot\nof PC1 and PC2 captures most of what's going on, so it's worth plotting.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nggplot(pca_df, aes(x = PC1, y = PC2, shape = Normal, color = Type)) +\n    geom_point(alpha = 0.6) +\n    theme(text = element_text(size = 18))\n```\n\n::: {.cell-output-display}\n![Samples projected onto the first two principal components, colored by cancer type and shaped by tumor/normal status.](geoquery_files/figure-html/fig-pca-1.png){#fig-pca fig-align='center' width=672}\n:::\n:::\n\n\nIn @fig-pca the x-axis is PC1 and the y-axis is PC2, each point is one sample,\ncolor marks the cancer type, and the shape marks tumor versus normal. The\ndominant pattern is **cancer type**: samples of the same color cluster together,\nso PC1 and PC2 are mostly separating tissues of origin from one another. Within\neach cancer type, the tumor and normal shapes tend to occupy slightly different\nregions, reflecting the tumor-vs-normal expression differences the original\nstudy set out to characterize. In other words, a handful of unsupervised\ncomponents, computed from just 500 genes, already recover biology you'd expect:\ndifferent cancers look different, and within a cancer, tumor looks different from\nnormal.\n\n## Summary\n\nYou just reused a published dataset from start to finish. You:\n\n- Downloaded GSE103512 from GEO with `getGEO()` and grabbed the dataset with\n  `[[1]]`.\n- Converted the legacy `ExpressionSet` into a `SummarizedExperiment` and\n  inspected its dimensions and sample annotations.\n- Summarized the cancer-type-by-tumor/normal design with `table()`.\n- Filtered to the 500 most variable genes, ran PCA with `prcomp()`, and read\n  the variance-explained plot.\n- Plotted PC1 vs. PC2 and saw the samples separate by cancer type, with\n  tumor and normal differing within each type.\n\nThe same recipe — fetch, load into a `SummarizedExperiment`, filter, reduce,\nplot — works for thousands of other GEO datasets.\n\n## Exercises\n\n::: {.callout-note collapse=\"true\"}\n## 1. Inspect the object\n\nWhat is the class of `se`, and what are the dimensions of its `assay` and\n`colData`? Which variables are stored in `colData`?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(se)\ndim(assay(se, \"exprs\"))   # genes x samples\ndim(colData(se))          # samples x annotation variables\ncolnames(colData(se))     # the available sample variables\n```\n:::\n\n\n`se` is a `SummarizedExperiment`. The assay has one row per gene and one column\nper sample; `colData` has one row per sample and one column per annotation\nvariable, including `cancer.type.ch1` and `normal.ch1`.\n:::\n\n::: {.callout-note collapse=\"true\"}\n## 2. Change the number of top genes\n\nRe-run the analysis keeping the top 100 genes, and again with the top 2000. Does\nthe PC1-vs-PC2 plot change much?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat100 <- assay(se, \"exprs\")[order(sds, decreasing = TRUE)[1:100], ]\npca100 <- prcomp(t(dat100))\nplot(pca100$x[, 1], pca100$x[, 2], xlab = \"PC1\", ylab = \"PC2\")\n```\n:::\n\n\nThe broad structure — samples separating by cancer type — is usually robust to\nthe exact cutoff. Too few genes can lose finer distinctions; too many let\nlow-variance noise creep back in. The stability of the big picture across\ncutoffs is itself reassuring.\n:::\n\n::: {.callout-note collapse=\"true\"}\n## 3. Plot more components with `ggpairs()`\n\nUse the `GGally` package's `ggpairs()` to view the first few principal\ncomponents together, colored by cancer type.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(GGally)\nggpairs(pca_df, columns = 1:4, mapping = aes(color = Type))\n```\n:::\n\n\n`ggpairs()` draws every pairwise combination of the chosen columns (here PC1–PC4)\nin a grid, so you can spot structure that PC1-vs-PC2 alone might hide — for\nexample, a cancer type that only separates along PC3 or PC4.\n:::\n\n[R]: https://cran.r-project.org/\n[GEOquery]: https://bioconductor.org/packages/GEOquery\n[GSE103512]: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE103512\n[multidimensional scaling]: https://en.wikipedia.org/wiki/Multidimensional_scaling\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}